### ISSUE TITLE
modelFor doesn't like / in names

### ISSUE THREAD

**Issue by devinus** [ember-engines/ember-engines#121]
E.g. `this.modelFor('accounts/show')` wont work, but `this.modelFor('accounts.show')` does.

**Comment by alexmasita** [comment]
In my ember engines app, this.modelFor('admin.tasks.bookings.view') within "admin.tasks.bookings.view.rooms.index" route file returns undefined.  Even just this.modelFor('admin') returns undefined.   In fact, when I view my ember engines app in the inspector, the routes tab does not display the routes.

Would appreciate if someone can shed some light on this:

The below is my route structure:

```sh
export default buildRoutes(function() {
    this.route('admin', function() {
        this.route('tasks', function() {    
            this.route('bookings', function() {
                this.route('view', { path: '/view/:booking_id' }, function() {
                    this.route('rooms', function() {
                        this.route('add');
                        this.route('edit', { path: '/edit/:room_id' });
                    });
                });
            });
        });
    });
});
```

My Environment is:
-------------------
Ember Inspector	2.0.4
Ember	2.8.2
Ember Data	2.9.0
jQuery	3.1.1
Ember Simple Auth	1.1.0
ReservationAdminEngineAddon	v0.0.2

**Comment by nathanhammond** [comment]
@alexmasita The issue you're reporting is distinct from the original report in this thread. Can you please move it to a new issue and delete the comment here so we can track them separately? (Otherwise we won't remember to address your issue.)

**Comment by bertdeblock** [comment]
I don't think `ember-engines` alters anything about the `modelFor` method on routes and AFAIK route names always need to be defined using dots instead of slashes. I think we can close this issue?
