### ISSUE TITLE
static content of in-repo engine's index.hbs rendered in the outer application.hbs {{outlet}}

### ISSUE THREAD

**Issue by tyronepost** [ember-engines/ember-engines#177]
Hi,

ember version: 2.6.0
ember-engines: 0.2.9

I created a routable in-repo engine in my application.  In the engine, I created an index route which had dynamic handlebars content and static html wrapper content.  I found when I navigate to the root page of my application outside of the engine, the static content of the routable engines index page is rendered.

~~Interestingly, I found that if I include a blank index.hbs file in the outer app, The phenomenon disappears.~~

**Comment by nathanhammond** [comment]
Can you please post a reproduction of what you're experiencing as a git repository which we can investigate?

**Comment by tyronepost** [comment]
git repo incoming.

**Comment by tyronepost** [comment]
> Interestingly, I found that if I include a blank index.hbs file in the outer app, The phenomenon disappears.

When I added the index route to the parent app, I had the server running, but this causes the code generated in index-engine/app/templates/index.js to change from
`export { default } from 'index-engine/templates/index';`
to 
`export default Ember.HTMLBars.template((function() {
  return {
    meta: {
      "fragmentReason": {
        "name": "missing-wrapper",
        "problems": [
          "wrong-type"
        ]
      },
      "revision": "Ember@2.6.2",
      "loc": {
        "source": null,
        "start": {
          "line": 1,
          "column": 0
        },
        "end": {
          "line": 2,
          "column": 0
        }
      },
      "moduleName": "index-test/templates/index.hbs"
    },
    isEmpty: false,
    arity: 0,
    cachedFragment: null,
    hasRendered: false,
    buildFragment: function buildFragment(dom) {
      var el0 = dom.createDocumentFragment();
      var el1 = dom.createComment("");
      dom.appendChild(el0, el1);
      var el1 = dom.createTextNode("\n");
      dom.appendChild(el0, el1);
      return el0;
    },
    buildRenderNodes: function buildRenderNodes(dom, fragment, contextualElement) {
      var morphs = new Array(1);
      morphs[0] = dom.createMorphAt(fragment,0,0,contextualElement);
      dom.insertBoundary(fragment, 0);
      return morphs;
    },
    statements: [
      ["content","outlet",["loc",[null,[1,0],[1,10]]]]
    ],
    locals: [],
    templates: []
  };
}()));`

**Comment by nathanhammond** [comment]
Thank you for the repository. We'll take a look and see if we can figure out what's happening.
