### ISSUE TITLE
Determine how to handle Route#serialize.

### ISSUE THREAD

**Issue by rwjblue** [ember-engines/ember-engines#22]
When a given route in an engine is being linked to, that routes `#serialize` method (see [API docs](http://emberjs.com/api/classes/Ember.Route.html#method_serialize)) is responsible for translating the provided model/object into the URL.

Example:

``` js
export default Ember.Route.extend({
  // use `model.slug` instead of `model.id`
  serialize(model) {
    return { id: model.get('slug') };
  }
});
```

---

One possible way to work around this would be to separate the serialization from the route object via a custom `route-serializer` object (that was a simple function).  Might look like this:

``` js
// addon/route-serializer/post.js

export function(model) {
  return { id: model.get('slug') };
}
```

And that file (like `addon/routes.js`) would be included at all times (aka not-lazily loaded).

**Comment by trentmwillis** [comment]
Just to make sure this is documented, there is an RFC for a variation of this proposal at emberjs/rfcs#120.

**Comment by mattmarcum** [comment]
Just wondering what the status of this is?  I saw that the rfc was merged but couldn't find any other references to the `route-serializer` object/function

**Comment by villander** [comment]
@dgeb can you close this?
