### ISSUE TITLE
in-repo engine jshintrc not honored

### ISSUE THREAD

**Issue by knownasilya** [ember-engines/ember-engines#254]
I added a `.jshintrc` with some globals defined, to my in-repo-engine, and it doesn't consume the config for the build. I'm weary of tightly coupling build related items like linting.

**Comment by nathanhammond** [comment]
@knownasilya What is the actual behavior for linting, and what is your expected behavior?

**Comment by trentmwillis** [comment]
@knownasilya any update on this? Also, since in-repo-engines are more-or-less in-repo-addons, can you verify that this is an ember-engines issue and not a generic ember-cli issue?

**Comment by bertdeblock** [comment]
@knownasilya Since JSHint isn't provided anymore by ember-cli, I think it's okay to close this?

**Comment by dgeb** [comment]
Agreed, thanks @bertdeblock!
