### ISSUE TITLE
Add integration/unit test resolver helper.

### ISSUE THREAD

**Issue by rwjblue** [ember-engines/ember-engines#267]
https://github.com/dgeb/ember-engines/pull/266 is good, but we should totally create a nice test helper to make this even easier.

I think adding something like:

```js
// addon-test-support/engine-resolver-for.js
import Resolver from 'ember-engines/resolver';

export function engineResolverFor(modulePrefix) {
  return Resolver.create({ namespace: { modulePrefix }});
}
```

@trentmwillis / @nathanhammond / @dgeb - Thoughts?

**Comment by trentmwillis** [comment]
This is more-or-less what I was originally working towards, just haven't had the time to finish it.

I would actually like for it to lookup the resolver defined by the Engine, in case the consumer is doing anything custom 😉 .

**Comment by trentmwillis** [comment]
This has been implemented for a while, closing.
