### ISSUE TITLE
Route-less Engine link-to scoping

### ISSUE THREAD

**Issue by trentmwillis** [ember-engines/ember-engines#272]
Currently, within a routable Engine `{{link-to}}` gets "scoped" to the Engine's `mountPoint`. However, this same behavior is not present for route-less Engines since they do not currently have a `mountPoint` since it is defined by the Router's DSL.

The question thus is: _should route-less Engines have `{{link-to}}` scoped in the same way as routable Engines?_

I am inclined to say yes, primarily for the two following reasons:

1. It makes behavior consistent across types of Engines.
2. It would force route-less Engines to use `link-to-external` which means explicit contracts about linking could be made between the host and the Engine.
3. Keeps route-less Engines from coupling to their host's route structure.

Note that this would mean that you effectively can't use `{{link-to}}` in route-less Engines, since they have no child routes.

Any other thoughts?

**Comment by mike183** [comment]
Was this topic ever discussed any further? We're beginning to utilise a significant number of routeless engines in our application, thus it would be good to get this locked down in order to future breaking changes.

**Comment by knownasilya** [comment]
I'm for this as well. All good points.

**Comment by mike183** [comment]
FWIW (as I never mentioned it in my previous reply), I also agree with all of @trentmwillis's points.

**Comment by trentmwillis** [comment]
I believe we need a member of the core team to chime in (*cough* @rwjblue *cough*). After that, I don't think implementation would be too difficult.

**Comment by rwjblue** [comment]
Sorry for missing this one. I agree with Trent's statement in the lead in description:

> The question thus is: should route-less Engines have {{link-to}} scoped in the same way as routable Engines?

_**YES!!!!**__

**Comment by mike183** [comment]
Thinking about this again, would it not be better to just assert if a `link-to` is used within a routeless engine?

**Comment by mike183** [comment]
@knownasilya @trentmwillis @rwjblue 

Thoughts on the above? I don't mind helping with implementation FWIW 🙂

**Comment by trentmwillis** [comment]
Seems good to me. Clear user feedback is always :100:.
