### ISSUE TITLE
link-to within Engine not working

### ISSUE THREAD

**Issue by lmcardle** [ember-engines/ember-engines#273]
I am not able to get link-to working within the engine for any route other than index. Here is a sample engine that demonstrates the issue: https://github.com/lmcardle/sample-ember-engine. The link-to is added inside the engine and is linking to a route, 'people', which is also inside the engine. The error I am getting says "there is no route named people."

**Comment by alexander-alvarez** [comment]
seems like you have to use `sample.people` and `sample.index`. not sure why
https://github.com/lmcardle/sample-ember-engine/blob/master/addon/templates/application.hbs#L6

**Comment by mike183** [comment]
Seems as though [this commit](https://github.com/dgeb/ember-engines/commit/482a39ec2a54a3ca4c081278456a624900ce971b#diff-0abc6c8a5e9729aeed5fb788fbeafb21) needs porting back to the 0.3.x.

Updating to 0.4.0 should fix your issue but I believe that release requires Ember v2.10.0+.
