### ISSUE TITLE
Unable to export services from engine addon to root application?

### ISSUE THREAD

**Issue by nmcclay** [ember-engines/ember-engines#278]
I have an in-repo-engine that can provide its own service to the root application.  However I'm unable to use any services provided by addons within my engine.  TLDR:

```
Engine Service -> Application -> OK
Addon Service -> Application -> OK
Addon Service -> Engine -> OK
Addon Service -> Engine -> Application -> NOT OK
```

In this specific case I was working on an authentication engine that handled user login/password reset etc, and provided a 'session' service that determined if the user was authenticated or not.  The session service is provided by the [ember-simple-auth](https://github.com/simplabs/ember-simple-auth) addon.  I've tried providing the dependency for ember-simple-auth to both the application and engine, but what I end up with appears to be a duplicate service, not a singleton.

What I'm seeing is that there is no way to provide a shared service from an addon within an engine with the root application.  This is unfortunate because it means I can't constrain the domain concerns of 'user authentication' within my auth engine.  Is this something that is possible with the current ember engines?  Is this a desirable behavior engine will ever support?

**Comment by murli2308** [comment]
I am facing the same issue when using ember-simple-auth with ember-engines ? Is there any way to extend the ember engines route with our auth route from main application ? This is basically to protect the ember engines route.

**Comment by trentmwillis** [comment]
From the description, I think there is a bug here, but not the one you're reporting.

Basically, you Engine shouldn't be able to provide Services to the host application at all. The reason being that if the Engine is lazy loaded, then you get weird, action-order-dependent behavior. So, not being able to use an addon service in the host application via an Engine sounds like correct behavior to me.

The correct architecture is to have Services passed "down" the application-engine tree if they need to be shared. You shouldn't ever pass things "up" as it violates the uni-directional dependency flow which makes lazy loading possible.

**Comment by nmcclay** [comment]
It's interesting to me that this is considered a bug, in a general sense I understand the value architecturally to be uni-directional but it makes the utility of splitting large monolith applications far less viable in my opinion.

Basically what I see being a tremendous value in engines is being able to isolate application concerns and 'publish' services to a core app that can be that can be distributed downwards to other engines.  Cross engine dependencies clearly causes issues no matter how you slice it, but from the perspective of being able to isolate all necessary dependency to the published API of the engine service makes reusing that work in other engines in your application much more portable.

I actually wrote a blog post about this topic and the [potential of engine service publishing/subscribing](http://development.wombatsecurity.com/development/2016/11/22/ember-engines/).  So any concern you are hearing isn't rooted in conceptual arechetural concerns, but a very real ambitious effort to rearchitect a large and complex sass product with dozens of developers around the ember engines paradigm.  A key challenge on that front is the sharing and consuming of logical dependencies that are managed as separate development teams.  The idea of using engines to split these application concerns along the lines of these teams while still conceptually having one logical application is highly desirable.  However I'm not certain how we would accomplish this if this binding for services is uni-directional as you mention.
