### ISSUE TITLE
Assertion Failed: Asset manifest does not list any available bundles.

### ISSUE THREAD

**Issue by phortx** [ember-engines/ember-engines#282]
I've created a standalone routable engine with ember-engines 0.4.0, ember-cli 2.10.0 and get this error if I call the engines index route (`/things/`).

`Assertion Failed: Asset manifest does not list any available bundles.`

Consumer App `router.js`:

```js
this.mount('things', { as: 'things' });
```

Engine App `routes.js`:

```js
this.route('index', { path: '/' });
```

The engine is 'installed' via a symlink in the `node_modules/` dir of the consuming ember-cli app. ([See here why](http://stackoverflow.com/questions/41165548/ember-engines-inside-rails-engines-via-ember-cli-rails/41180452#41180452)).

Any idea?

**Comment by phortx** [comment]
Just for fun I've tried to change the routes to test if that works ...

Consumer App `router.js`:

```js
this.mount('things', { as: 'things' });
```

Engine App `routes.js`:

```js
this.route('index', { path: 'new' });
```

I've called `/things/new` and got an UnrecognizedURLError ...

**Comment by phortx** [comment]
If I place a `console.log('ASDFASDFASASDF');` in the engines `index.js`, I can't see any output. Seems like it isn't loaded at all ...

**Comment by phortx** [comment]
Also created a StackOverflow question: http://stackoverflow.com/questions/41207713/cant-get-ember-engines-running

**Comment by mike183** [comment]
If you upload your app into a public repo it will be much easier for people to help. Sounds like a mis-configuration issue to me.

**Comment by phortx** [comment]
You're right. But it's a companies product so I can't simply upload it ;)

I'll try to setup a dummy project with the same architecture tomorrow and upload it.

**Comment by phortx** [comment]
As promised, here are the repos :)

- Engine: https://github.com/phortx/ember-engines-engine
- Consuming App with README: https://github.com/phortx/ember-engines-app

**Comment by mike183** [comment]
Looks like you've not added your engine as a dependency of your application in your applications `package.json`.

Try adding `"thingy-frontend": "*"` to your applications devDependencies.

**Comment by phortx** [comment]
Thank you for your answer, but that doesn't work:
`thingy-frontend` isn't in the npm registry, so npm can't find it (therefore the symlink)

Symlinking, adding the entry to the package.json and not running `npm install` will lead to a `Missing npm package` error while starting the app.

**Comment by mike183** [comment]
Sorry, I actually created a symlink using the same name as the package name. So the symlink in the `node_modules` directory should be called `thingy-frontend` instead of `ember-engines-engine`. You'll also need to make sure that you've run `npm install && bower install` in the `ember-engines-engine` directory.

The engine needs to be in the `package.json` in order to be mounted into the application.

Alternatively, you could either use an in-repo-engine or use [npm link](https://docs.npmjs.com/cli/link) to create the symlink.

**Comment by dmtask** [comment]
Thank you for your answer. I have just tested with phortx. This seems so half-way to work, we now get the following error:
`Uncaught Error: Could not find module `ember-engines/resolver` imported from `thingy-frontend/engine`
    at missingModule (loader.js:239)
    at findModule (loader.js:250)
    at Module.findDeps (loader.js:190)
    at findModule (loader.js:253)
    at requireModule (loader.js:20)
    at Class._extractDefaultExport (resolver.js:368)
    at Class.resolveEngine (resolver.js:184)
    at Class.resolve (ember.debug.js:5047)
    at resolve (ember.debug.js:2445)
    at Registry.resolve (ember.debug.js:1904)`

**Comment by mike183** [comment]
Looks like you're engine is using the old resolver from before the changes were moved upstream.

In your `addon/engine.js` file, import the resolver from `ember-resolver` instead of `ember-engines/resolver`.

**Comment by dmtask** [comment]
Ok, now we have the following error:
```
asset-manifest.js:19Uncaught Error: Failed to load asset manifest. For browser environments, verify the meta tag with name "frontend/config/asset-manifest" is present. For non-browser environments, verify that you included the node-asset-manifest module.
    at Module.callback (http://localhost:4200/assets/frontend.js:64:11)
    at Module.exports (http://localhost:4200/assets/vendor.js:140:32)
    at Module._reify (http://localhost:4200/assets/vendor.js:173:59)
    at Module.reify (http://localhost:4200/assets/vendor.js:159:27)
    at Module.exports (http://localhost:4200/assets/vendor.js:138:10)
    at requireModule (http://localhost:4200/assets/vendor.js:32:18)
    at http://localhost:4200/assets/vendor.js:92485:20
    at Array.forEach (native)
    at exports.default (http://localhost:4200/assets/vendor.js:92482:8)
    at Module.callback (http://localhost:4200/assets/frontend.js:21:41)
```

I have create a meta-tag in the app index.html, like this:
`<meta name="thingy-frontend/config/asset-manifest" content="asset/asset-manifest.json">` -> same error. (The path in content is advised...)

What can i do? :)

**Comment by mike183** [comment]
You shouldn't need to manually insert the meta tag into the page, it should be inserted automatically.

After following the previous steps on your reproduction repos, I'm not seeing the error you have above.

What does the page source for the page look like? For example, for me, the resulting page source from your repos is

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Frontend</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <base href="/" />
<script src="/ember-cli-live-reload.js" type="text/javascript"></script>
<meta name="thingy-frontend/config/environment" content="%7B%22modulePrefix%22%3A%22thingy-frontend%22%2C%22environment%22%3A%22development%22%7D" />

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/frontend.css">

    <meta name="frontend/config/asset-manifest" content="%7B%22bundles%22%3A%7B%7D%7D" />
  </head>
  <body>
    

    <script src="assets/vendor.js"></script>
    <script src="assets/frontend.js"></script>

    
  </body>
</html>
```

**Comment by phortx** [comment]
@mike183 Thank you very much for you guidance! You helped us a lot :)

**Comment by dmtask** [comment]
@mike183 Also from me, thank you very much :)

**Comment by dmtask** [comment]
My Page Sourcecode:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Frontend</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <base href="/" />
<script src="/ember-cli-live-reload.js" type="text/javascript"></script>
<meta name="thingy-frontend/config/environment" content="%7B%22modulePrefix%22%3A%22thingy-frontend%22%2C%22environment%22%3A%22development%22%7D" />

    <link rel="stylesheet" href="assets/vendor.css">
    <link rel="stylesheet" href="assets/frontend.css">

    <meta name="frontend/config/asset-manifest" content="%7B%22bundles%22%3A%7B%7D%7D" />
  </head>
  <body>
    

    <script src="assets/vendor.js"></script>
    <script src="assets/frontend.js"></script>

    
  </body>
</html>
```

**Comment by mike183** [comment]
Hmm, the asset manifest is included in the page so I'm not sure why you would be seeing that error.

Are you able to update the reproduction repos to show the new error?

**Comment by dmtask** [comment]
Repo are updated :)

**Comment by trentmwillis** [comment]
I think the root issue here is that the Engine isn't lazy loading and thus there are no additional assets from which to create an asset manifest. This is a bug, as you shouldn't need to use a lazy loading Engine in order to use ember-engines.

**Comment by mike183** [comment]
@dmtask: Removing the `ember-engines` dependency under `dependencies` seems to fix the issue. You already have it listed under `devDependencies` anyway.

@trentmwillis: I don't seem to have any issues using eagerly loaded engines. I've only experimented with them lightly, but I've not seen any issues.

**Comment by dmtask** [comment]
@mike183: Ok, i will try at. Thank you.

**Comment by dmtask** [comment]
@mike183: I've tested it, but it does not work. There is the same error ...

**Comment by dustyjewett** [comment]
I have the same issue, but with in-repo addons:

https://github.com/dustyjewett/ember-engines-in-repo

**Comment by trentmwillis** [comment]
@phortx I opened a PR to fix your issue. At this point, I don't think this is a bug, just some misconfiguration in the reported cases: https://github.com/phortx/ember-engines-engine/pull/1.

I'll open a PR to the website soon to better document the setup.

**Comment by dmtask** [comment]
@trentmwillis: I test it and report back. :)

**Comment by dmtask** [comment]
@trentmwillis: Thank you very much, it works now. :)

**Comment by phortx** [comment]
@trentmwillis Kudos!

**Comment by brunowego** [comment]
I get similar issue with `ember-engines` v0.5.0-beta.10. I put a demo to debug here: https://github.com/brunowego/ember-site-engine

**Comment by jonnedeprez** [comment]
@brunowego I also had this issue (being stuck at v0.5.0-beta.9), but since I upgraded to the latest version of ember-cli I no longer see it. Now using v0.5.0.

**Comment by jacefarm** [comment]
Following @brunowego & @jonnedeprez...

As Ember Engines is experimental and being developed against the master branches of Ember and Ember-CLI, be sure that you are using **[compatible versions](https://github.com/ember-engines/ember-engines/blob/master/README.md#important-note-about-compatibility-and-stability)**.

**Comment by johnpaulh** [comment]
hi all, i too got the same error.  I am using ember-cli 2.16.2 and does n't wish to downgrade to 2.12.x(compatible version for v.0.5.0)), i tried using the ember-cli 2.18.0 LTS with ember-engine v0.5.1 the errors went away. I found in ember-engine package.json, there is support for ember-cli 2.14.2 in the release tag v.0.5.14 and then it jumped to 2.18 LTS. Does ember-cli 2.16.2 supported ? I am new to ember-engines. any help is appreciated.

**Comment by teejayhh** [comment]
I have the same issue with ember 3.5. So I guess ember-engines is not ready for prime time just yet, or was it ever ?

**Comment by Leooo** [comment]
adding back "ember-addon" keyword in our engines, instead of (or in addition to) "ember-engine" fixed it, on our side.
