### ISSUE TITLE
Inconsistency with link-to component

### ISSUE THREAD

**Issue by xm** [ember-engines/ember-engines#285]
The route passed into the link-to component does not require the engine name (relative) but in order for current-when to work properly, you need to pass in the engine name + route (absolute). This seems like an inconsistency that should be changed. 

Example:
```{{#link-to 'route' current-when='engine.route'}}```

Ember 2.10.1
Engines 0.4.0

**Comment by trentmwillis** [comment]
Yep, this should be improved. The fix should be relatively straightforward, just add some prefixing logic for the `currentWhen` property similar to [what we do for the target route](https://github.com/ember-engines/ember-engines/blob/1b36714653fbc395db23b849058617c31d778fed/addon/-private/link-to-component.js#L17-L21).

If you could PR with a failing test and fix, it would be much appreciated!

**Comment by mike183** [comment]
I have a fix for this working on local, will submit a PR later once I've had a chance to look at putting together a failing test.

**Comment by trentmwillis** [comment]
Thanks @mike183! Going to assign this to you then.

**Comment by mike183** [comment]
Just submitted a PR, not sure that the test is as good as it could be though...
