### ISSUE TITLE
Improve documentation on engine-addon development workflow

### ISSUE THREAD

**Issue by mydea** [ember-engines/ember-engines#307]
I have started out with in-repo engines, which were really easy to setup and get started.
Now, I wanted to use the lazy loading feature, so I migrated them to dedicated addons. However, it turned out that wasn't as straight-forward as I imagined it to be. So I figured the things I "missed" there could also be missed by others, so they might as well go into the README. I'll make a PR with the information I gathered, but wanted to verify a few things so that the information I write there is correct ;)

1. All dependencies of the host app need to go into the engine's devDependencies
2. All dependencies of the engine need to go into the engine's dependencies
a.) Everything in the dependencies will be included in the lazy loaded bundle
b.) Nested dependencies do not work correctly. For example, if an engine has a dependency A, which itself has the dependency "ember-d3" (which loads D3.js), then D3.js will not be correctly loaded in the engine. Instead, you need to also include ember-d3 as dependency of your engine.
c.) Remove the `ember-disable-prototype-extensions` addon from the engine
5. "ember-engines" should additionally to devDependencies, also go into "peerDependencies"
6. The engine's dummy app should be setup like the host app

**Comment by trentmwillis** [comment]
@mydea thanks for documenting this stuff! We're actively trying to move all documentation into the [ember-engines.com](https://github.com/ember-engines/ember-engines.com) website so that we have a single source of truth, so could you re-open this issue over there? That way we can make sure it finds a place in the correct context of the rest of the docs.

**Comment by mydea** [comment]
I moved it over!
