### ISSUE TITLE
Route-less in-repo engine not working on Ember 2.7 / ember-engines 0.2.12

### ISSUE THREAD

**Issue by benoror** [ember-engines/ember-engines#308]
Hi! I wanted to try out engines today on our commercial app, but when mounting my route-less component via `{{mount 'engine-name'}}` I get this Exception:

```
You used `{{mount 'engine-name'}}`, but the engine 'engine-name' can not be found.
```

I installed version `0.2.12` (latest `0.2.x`, compatible with Ember 2.7 [as explained here](https://github.com/ember-engines/ember-engines#important-note-about-compatibility-and-stability)) then ran `ember g in-repo-engine engine-name`, then deleting the router-related stuff.

Any idea? Thanks!

**Update**: Might be related: https://github.com/ember-engines/ember-engines/issues/232

**Comment by nathanhammond** [comment]
Closing as we're not actively supporting old branches.
