### ISSUE TITLE
Engine build failing on app.import in addon

### ISSUE THREAD

**Issue by dbashford** [ember-engines/ember-engines#320]
Have this in an addon

```javascript
app.import('some/font/file', { destDir: 'assets/fonts/' });
```

Addon is pulled into engine. Breaks the build in the engine. Same addon is yanked into our app, no issues there.

```javascript
Build failed.
The Broccoli Plugin: [Funnel: Funnel 
  vendor/fonts
  assets/fonts/
 include:40] failed with:
Error: ENOENT: no such file or directory, scandir '/path/to/tmp/funnel-input_base_path-SxxPiXez.tmp/vendor/fonts/'
```

Simply creating the `vendor/fonts` folder in the engine fixes the issue, so this is low priority assuming it's an issue at all and not just something I'm missing.

**Comment by trentmwillis** [comment]
What version of `ember-engines` are you using? I believe this is likely related to https://github.com/ember-engines/ember-engines/pull/317.

**Comment by dbashford** [comment]
I am using `0.4.0`. I can try this change and see if it fixes things.

To be clear, you are saying that the `app.import`s [that are documented here](https://ember-cli.com/extending/#importing-dependency-files) should instead be `this.import`s?

**Comment by dbashford** [comment]
That fixes the issue. If you feel that the warning, which I'm guessing will come before this error, is sufficient messaging to the user letting them know what to do, then you can close this.

Thanks!

**Comment by trentmwillis** [comment]
I believe it should be enough. Closing for now, if it becomes a more common issue we can find additional steps to improve.
