### ISSUE TITLE
Brainstorm session on unifying app and engine style pipelines...

### ISSUE THREAD

**Issue by rwjblue** [ember-engines/ember-engines#322]
After a pairing session with @stefanpenner which mostly focused on aligning the styles generation, hooks being called, etc we came up with the following proposed result.  Still very much WIP and somewhat still in my brain, but I'll be working on this over the next day or so...

---

Normal App (also runs for eager engines) 
----------
1. build up addonTreesFor('styles')
1. process `app/styles`
1. merge trees from #1 and #2 above.
1. invoke preprocessTree('css', ...)
1. process registry of CSS preprocessors
1. concat into `options.outputPaths.app.css`
1. process things that were `app.import`'ed (e.g. `assets/vendor.css`)
1. prod ? preprocessMinifyCss : null
1. invoke postprocessTree('css', ...)

Lazy Engines (today)
------------
1. `this.compileStyles(this._treeFor('addon-styles'));`
  * preprocessTree('css', ...)
  * `processCss` (main registry processors e.g. sass)
  * postprocessTree('css', ...)
1. concat `**/*.css` -> `engines-dist/<engine-name>/assets/engine.css`
1. `this.eachAddonInvoke('treeFor', ['addon'])` as `vendor`
1. concat `**/*.css` from vendor -> `engine-dist/<engine-name>/assets/engine-vendor.css`
1. process `app.import`ed styles

Lazy Engines (Proposed)
----------
1. build up addonTreesFor('styles') *Note: not required for today*
1. process `treeFor('addon-styles');`
1. merge trees from #1 and #2 above
1. invoke preprocessTree('css', ...)
1. concat `**/*.css` -> `engines-dist/<engine-name>/assets/engine.css`
1. `this.eachAddonInvoke('treeFor', ['addon'])` as `vendor`
1. process things that were `app.import`'ed (e.g. `assets/vendor.css`)
1. prod ? preprocessMinifyCss : null *Note: unclear if this is needed at the lazy engine level AND the app level?*
1. invoke postprocessTree('css', ...)

**Comment by nathanhammond** [comment]
Note that:

> 3. concat **/*.css from vendor -> engine-dist/<engine-name>/assets/engine-vendor.css

...should only apply one level deep. Other than that it should be only the `addon-name.css` which should be present in that hook.
