### ISSUE TITLE
Deduplicate Addon Assets

### ISSUE THREAD

**Issue by trentmwillis** [ember-engines/ember-engines#329]
Currently, when an addon is included in multiple locations with lazy Engines, that addon's code is duplicated. This problem breaks down into two scenarios:

1. Duplication when **a parent and child** have the same addon. This is easy to solve, as the parent copy should be the only copy, since it is guaranteed to be loaded first.

2. Duplication when **siblings** have the same addon. This is difficult to solve as we can't make assumptions as to which Engine will be loaded first. There are three potential approaches in this scenario:

    * Include the asset in both Engine bundles -> this is easy to implement and use (and is our current reality), but has negative impact on asset download size for our users. Also has potential to run into weird, state issues by clobbering previously loaded copies of the module.
    * Bundle shared assets separately and load with first Engine that needs them -> relatively easy to implement and use, but can incur multiple network requests for potentially small assets. The Asset Manifest/Loader has easy support for this use case.
    * Hoist shared assets into the closest common ancestor's bundle -> no more difficult to implement than the above, but bloats the main assets with potentially unused features. Also can make it difficult to reason about where assets wind up.

It is likely that each of the above approaches can be good or bad depending on circumstances.

Thus, we need to discuss and arrive at a solution for deduplication in **sibling** engines. The **parent and child** scenario just needs to be implemented.

**Comment by cibernox** [comment]
Point one is crystal clear, agree.

About point 2, I think that all three approaches are valid options depending on your app. I don't think there is a single solution. 'd like the decission to be in the hands of the developer. Ideally expressed just in terms of package.json, but I don't know if it will be doable.

By example, the last option, hoist shared addons to the parent app is as simple for the user as include that addon in the package.json of the parent app. That would mean we're now in point 1, in which we agree there it should be hoisted.

However repeat the addon or bundle it as a separate file is tricky and will probably depend on your app and the addon. An entra request might make sense for big addons, not so much for those that just give you a couple helpers. It will become more and more if your app leverages SW download deltas between versions.

Without giving it too much though I think that the default approach for duplicated addons that are not in the parent app could stay as today and duplicate them, and if the user wants to bundle some addons separately those can be listed in some sort of special config key, either in the package.json or in the ember-cli-build.js of the host app.

**Comment by trentmwillis** [comment]
A PR has been opened for Point 1: https://github.com/ember-engines/ember-engines/pull/356.

For Point 2, I think the approach @cibernox outlines is good. Which means for the 3 scenarios I outline above we have:

1. **Duplicate**: This is, and will continue to be, the default behavior for sibling issues.
2. **Hoist**: Define the dependency in both Engine and host, and the solution to Point 1 will deduplicate the shared code.
3. **Separate bundle**: We should determine an API for allowing the Application to specify which addons should be separately bundled. This will only apply to addons included by Engines. Anything that is a dependency of the application will just be included in the initial payload (again, Point 1).

**Comment by trentmwillis** [comment]
#356 has been merged. Some additional edge cases came up in that PR that still need to be addressed. Linking them here so they aren't forgotten:

1. https://github.com/ember-engines/ember-engines/pull/356#issuecomment-288571816
2. https://github.com/ember-engines/ember-engines/pull/356#issuecomment-288645644

**Comment by gokatz** [comment]
On a related note, can I **duplicate** the dependencies for my engine? 

I'm trying to build an engine separately. Since the Deps of the engine and dummy app will be the same, the generated vendor files (js and css) will always be same. It makes impossible to inject an engine into an actual consuming app without marking it as an explicit dependency. Can I make a standalone build for an engine?

**Comment by JoseWebby** [comment]
Hi @gokatz - Did you had any luck with building engine standalone and using alongside the host app?

**Comment by gokatz** [comment]
AFAIK, this is not yet supported in Engines yet, @JoseWebby 
I switched to another stack instead.

**Comment by villander** [comment]
It was fixed by #595 

can you close it @rwjblue @dgeb ?
