### ISSUE TITLE
Where put the settings from addon in engine?

### ISSUE THREAD

**Issue by brunowego** [ember-engines/ember-engines#346]
I have trying use `ember-cli-webfont` inside a "engine" to generate icon fonts. Outside "engine" works with the follow settings:

```js
/* eslint-env node */
const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = (defaults) => {
  const app = new EmberApp(defaults, {
    webfont: {
      path: 'app/icons',
      options: {
        templateOptions: {
          classPrefix: 'i--',
          baseClass: 'i'
        }
      }
    }
  });

  return app.toTree();
};
```

This is possible or I need generate outside "engines"? Thanks!

**Comment by XaserAcheron** [comment]
Huh, good timing. I just ran into this yesterday with `ember-font-awesome`; its settings are also configured in `ember-cli-build.js` as above, but I've no idea where (if possible) to do this in an engine (there's one particular setting needs to be to enabled in just the engine, not the host app, for reasons).

Is this something `ember-engines` can/will be able to handle? Or should we humbly beseech the addon authors for support here?

**Comment by brunowego** [comment]
I think the `ember-engines` can handle it.

**Comment by brunowego** [comment]
I put here https://github.com/vitch/ember-cli-webfont/issues/3 a example. It's works.

**Comment by bertdeblock** [comment]
I think we can close this? Configuring other addons should be possible by putting the config inside the engine's `index.js` file, taking into account of course that said addon supports being a nested dependency.
