### ISSUE TITLE
External links to routes with dynamic segments

### ISSUE THREAD

**Issue by XaserAcheron** [ember-engines/ember-engines#349]
See title. I'm trying to create a link within an engine that takes users back to their "homepage" (i.e. a route in the host application), but said page has a dynamic segment in the URL (tenant name; it's a multi-tenant app). It doesn't seem like external links have this functionality (or, if it does, it's undocumented and well-hidden ;), hence this humble-ish feature request.

I can currently fiddle around this with a shared service, but that's a bit uglier than I'd like.

**Comment by trentmwillis** [comment]
The `{{link-to-external}}` helper should be functioning similarly to a normal `{{link-to}}` and you should be able to pass in any params you normally would. If this does not seem to be working for you, then a reproduction would be most helpful here.

**Comment by XaserAcheron** [comment]
Huh. Well, sure enough, it works after all -- must've done something wrong the first time I tried it.

It may be worth adding a short example to the guide. I'd come to the conclusion this wasn't supported after trying, failing, and not seeing any mention of it on the relevant pages.

Closing officially though since this does indeed exist. :P

**Comment by trentmwillis** [comment]
If you feel it should be added to the guides, please open a PR, it would be much appreciated!

**Comment by XaserAcheron** [comment]
I'll put it on the rainy-day list.

Peeking at the code, it warms my heart that the guide is, itself, an engine. :D
