### ISSUE TITLE
Parameters required for generating dynamic segments

### ISSUE THREAD

**Issue by brunowego** [ember-engines/ember-engines#351]
After upgrade to `0.5.0-beta.10`, I start getting the below errors:

```
"Assertion Failed: You attempted to define a `{{link-to "enterprise.index"}}` but did not pass the parameters required for generating its dynamic segments. There is no route named enterprise.index"
```

Going back to `0.5.0-beta.9`. My all dependencies below:

```js
{
  ...
  "devDependencies": {
    "broccoli-asset-rev": "~2.5.0",
    "ember-ajax": "~2.5.5",
    "ember-cli": "~2.12.0-beta.1",
    "ember-cli-app-version": "~2.0.1",
    "ember-cli-babel": "~5.2.4",
    "ember-cli-dependency-checker": "~1.3.0",
    "ember-cli-eslint": "~3.0.2",
    "ember-cli-htmlbars": "~1.1.1",
    "ember-cli-htmlbars-inline-precompile": "~0.3.6",
    "ember-cli-inject-live-reload": "~1.6.1",
    "ember-cli-qunit": "~3.1.1",
    "ember-cli-sass": "~6.1.1",
    "ember-cli-shims": "~1.0.2",
    "ember-cli-sri": "~2.1.1",
    "ember-cli-uglify": "~1.2.0",
    "ember-cli-webfont": "~0.0.3",
    "ember-data": "~2.12.0-beta.4",
    "ember-engines": "~0.5.0-beta.9",
    "ember-export-application-global": "~1.1.1",
    "ember-load-initializers": "~0.6.3",
    "ember-resolver": "~2.1.1",
    "ember-simple-auth": "~1.2.0",
    "ember-simple-auth-token": "~2.1.0",
    "ember-source": "~2.12.0-beta.2",
    "ember-truth-helpers": "~1.3.0",
    "loader.js": "~4.2.2"
  },
  "engines": {
    "node": ">= 6.10.0"
  }
  ...
}
```

**Comment by rwjblue** [comment]
Can you put together a demo repo for us to look at?  Are you saying that things worked properly on 0.5.0-beta.9, but not on 0.5.0-beta.10?  Any other dependencies change?

The changes from -beta.9 to -beta.10 were almost exclusively related to CSS handling. I'm not sure why those changes would trigger this error.

**Comment by brunowego** [comment]
Is a corporative project. I know now that is a issue with another addon. Thanks @rwjblue 👍

**Comment by brunowego** [comment]
@rwjblue, I put a demo on https://github.com/brunowego/ember-site-engine. If have a time, try debug this.

**Comment by brunowego** [comment]
Just change `0.5.0-beta.10` to `0.5.0-beta.9`and will work.

**Comment by brunowego** [comment]
This issue occur too in `Routeable Engine` demo.

**Comment by brunowego** [comment]
@trentmwillis can you help me with this? Thanks!

**Comment by brunowego** [comment]
I finded my mistake. I am trying to test the routable engine inside the dummy app, only thing I forgoten is create the `application.js` and `application.hbs` inside the dummy app. 

After this everthing works.

Thanks and sorry for disturbing...
