### ISSUE TITLE
treePath is hardcoded to a path instead of using the originally defined treeForAddon

### ISSUE THREAD

**Issue by jsturgis** [ember-engines/ember-engines#355]
[engine-addon.js#L129](/ember-engines/ember-engines/blob/master/lib/engine-addon.js#L129) is using a hardcoded path `var treePath = path.resolve(this.root, this.treePaths['addon']);` instead of using the output of the originally defined `treeForAddon` function. This makes it difficult for an engine to modify it's build.

I spoke with @rwjblue about this on slack and he confirmed it is a bug.

**Comment by trentmwillis** [comment]
@jsturgis would you mind attempting a PR for this? We can provide support if needed.

**Comment by jsturgis** [comment]
@trentmwillis yeah no problem I'll start on this now.
