### ISSUE TITLE
validation in ember-cp-validations not found

### ISSUE THREAD

**Issue by jnfingerle** [ember-engines/ember-engines#359]
Hi,

_I'm sorry. My first try to generate a minimal test case was broken. Now for real:_

Using ember-cp-validations (added to both package.json-s) inside an in-repo-engine I get a "TypeError: owner.factoryFor is not a function". This is not related to any store/model-problems; I'm trying to use those validations on a "simple" Ember object.

**Example:** 
* Code: https://github.com/jnfingerle/problem-engine-validation
* Error: visit http://localhost:4200/test-engine
* Same code without engine: visit http://localhost:4200/

I'm not sure, if there is an error on my side, in ember-cp-validations of ember-engines. 

Cheers, jnfingerle

**Comment by jnfingerle** [comment]
OK, this works now with ember 2.12 and ember-engines 0.5.0

**Comment by Sandeeprao69** [comment]
Hey i am still getting this error?
I am injecting the validation mixin into controller of Ember engine but am getting error.
any help/suggestions would be appreciated

**Comment by jnfingerle** [comment]
@Sandeeprao69 could you be a bit more specific? - Which versions are you using? What is the exact wording of your error message? Do you have a testcase?

_JFTR: I'm only a user of ember-engines._

**Comment by Sandeeprao69** [comment]
Hey I am using Ember 2.11 and Ember-engine 0.4.0 .
I am getting error saying owner.factoryFor is not a function when i try to access validate() methon controller by doing this.validate().

**Comment by Sandeeprao69** [comment]
Below is my validation file.

`import { validator, buildValidations } from 'ember-cp-validations';
const { computed } = Ember;
const guestValidation = buildValidations({
    'guest.email': [
        validator('presence', true),
        validator('format', {
            type: 'email',
            message: 'Please enter a valid email address'
        })
    ],
    'guest.firstName': [
        validator('presence', true),
    ],
    'guest.lastName': [
        validator('presence', true),
    ],
    'guest.dateOfBirth': [
        validator('presence', true),
        validator('date', {
            before: 'now',
            after: computed(function() {
                return moment().subtract(120, 'years').format('M/D/YYYY');
            }).volatile(),
            message(type, value /*, context */ ) {
                if (type === 'before') {
                    return 'Are you from the future?';
                }
                if (type === 'after') {
                    return `There is no way you are ${moment().diff(value, 'years')} years old`;
                }
            }
        })
    ],
    'guest.phoneNumber': [
        validator('presence', true),
        validator('length', {
            min: 10,
            max: 10
        })
    ],
    'guest.title': [
        validator('presence', true)
    ]

});

export default guestValidation;`

**and Controller is** 


import Ember from 'ember';
import newUserValidation from '../../validators/sign-up-validations';

export default Ember.Controller.extend(newUserValidation, {
 guest: Ember.Object.create({
        title: "",
        firstName: "",
        middleName: "",
        lastName: "",
        suffix: "",
        dateOfBirth: "",
        gender: "",
        email: "",
        phoneNumber: "",
        allowCompanywideAccess: "",
        sendEmailToGuest: "",
        gender: 'male'
    }),
actions(){
saveGuest(){
this.validate().then(Rest code.......)
}

}
 });

**Comment by jnfingerle** [comment]
@Sandeeprao69 I don't believe that the validation file is relevant for this problem. Anyway, ember 2.11 / ember-engine 0.4.0 was the combination that lead to my bug report. But like I said, the problem went away with ember 2.12 / ember-engine 0.5.0.

**Comment by Sandeeprao69** [comment]
Hey thanks, It worked when i have upgraded to 2.12 and 0.5.0 :)
