### ISSUE TITLE
Support URL's in Route#transitionTo?

### ISSUE THREAD

**Issue by rwjblue** [ember-engines/ember-engines#36]
Currently, we throw an error if the first argument "resembles a URL".  Should we change this behavior and allow URL based transitions?  What are some use-cases where this is important?

**Comment by bertdeblock** [comment]
@rwjblue I was going through some issues and was wondering if this one is still relevant? Since the transition methods on routes will be deprecated and an engine router is in the works.

**Comment by rwjblue** [comment]
Yep, totally right
