### ISSUE TITLE
link-to helper's current-when property has inconsistent behavior when passing in multiple routes

### ISSUE THREAD

**Issue by xm** [ember-engines/ember-engines#373]
The first path is treated as relative, while the remaining paths are treated as absolute. 

The bug is how current-when is handled here: https://github.com/ember-engines/ember-engines/blob/da05713bfbd7ca5d415623b1bb4160c34c842be0/addon/components/link-to-component.js#L22-L24

Example of the bug (see the README): https://github.com/xm/current-when-bug

**Comment by trentmwillis** [comment]
Ah, did not realize you could add space-separated values to `current-when`. Definitely a bug; thanks for the great reproduction!

Would you mind taking a stab at fixing? Should be relatively straight-forward I think.

**Comment by xm** [comment]
@trentmwillis I will try to get a fix up
