### ISSUE TITLE
Nested Ember Engines

### ISSUE THREAD

**Issue by balgev** [ember-engines/ember-engines#377]
Hi Ember masters. 

Now I am using Ember-engines, which seem to be really powerful and amazing. 

There is one question I want to ask. Is there an Ember generator to generate nested engines? 

For examples I have ‘sportsbook-engine’ in my app and now I want to create sub-engines ‘sportsbook-live’ and ‘sportsbook-prematch’. 

Please suggest me the right way to do that. 
Thanks

**Comment by Vazgen7788** [comment]
Here is an example of nested engines. But I'm not sure is this right way.
https://github.com/Vazgen7788/ember-nested-engines-experiment

**Comment by dgeb** [comment]
Have you gone through the guides? http://ember-engines.com/guide

There are instructions for creating engines as addons (standalone or in-repo).

Routable engines can be nested inside apps or other routable engines.

Route-less engines can be nested inside templates in apps or engines.

Please review the guides and raise issues if you have specific problems. Please ask questions in the #ember-engines channel of community slack.
