### ISSUE TITLE
Getting "Unknown blueprint" when running ember g 

### ISSUE THREAD

**Issue by dshrestha** [ember-engines/ember-engines#383]
I am trying out ember engine for the first time. I created a dummy engine called "studio-reporting" following the instructions provided in http://ember-engines.com/guide

Since the addon is in my local machine, I changed my directory to the engine folder and then ran "npm link". Then I changed my current directory to the consuming ember app and ran "npm link studio-reporting". 
Then when I ran ember g studio-reporting, it shows me "Unknown blueprint: studio-reporting" error.

I am using ember-cli 2.12.1

**Comment by Iswaryasl** [comment]
Facing the same issue

Cli version details:
ember-cli: 3.26.1
node: 12.4.0
os: darwin x64

Can someone help on this

**Comment by bertdeblock** [comment]
@Iswaryasl Why do you want to run `ember g some-engine-name`?

**Comment by Iswaryasl** [comment]
I m trying to create in-repo-engines in ember

```ember generate in-repo-addon super-blog```


While running this command only I m getting the error "Unknown blueprint: in-repo-engine"

**Comment by bertdeblock** [comment]
Have you already installed the `ember-engines` package itself? The `in-repo-engine` blueprint comes from that package.

**Comment by Iswaryasl** [comment]
No ..
Will try... Thank you

**Comment by Iswaryasl** [comment]
Working after installing ember-engines.
Thank you
