### ISSUE TITLE
Error message: routeHandler.get is not a function

### ISSUE THREAD

**Issue by rmachielse** [ember-engines/ember-engines#385]
I am seeing this error when I open the ember inspector routes tab with an engine mounted into the app, even without navigating to the engine.
I tried to eliminate the error by removing routes/controllers etc from the engine but nothing seems to help. Only when I remove the entire `this.mount` statement from the app router the error disappears.

The error is being thrown from [this line](https://github.com/emberjs/ember-inspector/blob/master/ember_debug/route-debug.js#L141).
The issue is particularly hard to debug as the error is thrown from the chrome extension, which doesn't let me place breakpoints.

![schermafbeelding 2017-03-27 om 10 45 04](https://cloud.githubusercontent.com/assets/2470404/24350599/1907c676-12e3-11e7-8c71-2b52c474b397.png)

I am using ember and ember-cli 2.12 and ember-engines 0.5.0

**Comment by rmachielse** [comment]
I discovered that the `router.getHandler` returns a Promise when the route corresponds to an engine that has to be instantiated first. This is an asynchronous operation, while the `buildSubTree` function is synchronous. It will probably require more work to make all of that asynchronous as well? Should I move this issue to the ember-inspector project?

**Comment by rmachielse** [comment]
@rwjblue @trentmwillis did anyone of you see this issue before? Would a pr to ember inspector be a desired solution?

**Comment by trentmwillis** [comment]
Yeah, this is an issue with ember-inspector. We haven't made any modifications to the inspector in order to make it work properly with engines (and particularly lazy engines), so things that are asynchronously resolved are going to be problematic (note: all routes for engines are asynchronously resolved, even if not lazy so that you get uniform behavior).

**Comment by rmachielse** [comment]
@trentmwillis so is a pr on ember-inspector making the route reporting asynchronous desired?

**Comment by bravo-kernel** [comment]
Hit this as well, thanks for clarifying. @rmachielse nice to make acquaintance btw

**Comment by trentmwillis** [comment]
@rmachielse I would imagine so; that way apps using engines can still use the inspector. That said, it'd be best to open an issue with that repo to pursue it.

**Comment by mike183** [comment]
FWIW there is already an issue open in the ember-inspector repo about engines support in general. Though there hasn't been a great deal of discussion. See emberjs/ember-inspector#632

**Comment by trentmwillis** [comment]
Thanks, @mike183. I'm going to close this as I don't believe this is an issue with ember-engines itself, but if anything is needed from the ember-engines side to fix ember-inspector we can provide support.

**Comment by rmachielse** [comment]
@mike183 @trentmwillis ok, I will continue the discussion there 👍
