### ISSUE TITLE
Cant have the same template name in main app and ember engine

### ISSUE THREAD

**Issue by scottharris86** [ember-engines/ember-engines#395]
as a simple example. lets say we create a simple ember app. like the one form the guides.. we add the scientists route and show a simple h2.. now if i create admin engine. and add a scientist route.. this would be standalone engine. with a different h2 in the scientist template. install the engine in the main app. ember s... i get a template exists error.... i think this is kind of crazy... in the main app. i may want a user to see all scientists only related to their account... but in an admin app i would want to see all scientists.. am i thinking about engines wrong? i feel like it should be properly name spaced and not create a collision. i would want to have many of the same routes except their behavior, look, and actions would e different depending on if i was a user in the main app or an admin behind admin/*

The Broccoli Plugin: [broccoli-persistent-filter:TemplateCompiler] failed with:
Error: EEXIST: file already exists, symlink '/Users/scott/Development/ember-quickstart/node_modules/scientist-admin/app/templates/application.js' -> '/Users/scott/Development/ember-quickstart/tmp/broccoli_persistent_filtertemplate_compiler-output_path-lNI3HQki.tmp/ember-quickstart/templates/application.js'
at Object.fs.symlinkSync (fs.js:1034:18)
at symlink (/Users/scott/Development/ember-quickstart/node_modules/symlink-or-copy/index.js:98:14)
at symlinkOrCopySync (/Users/scott/Development/ember-quickstart/node_modules/symlink-or-copy/index.js:65:5)
at TemplateCompiler.Filter._handleFile (/Users/scott/Development/ember-quickstart/node_modules/broccoli-persistent-filter/index.js:178:12)
at TemplateCompiler. (/Users/scott/Development/ember-quickstart/node_modules/broccoli-persistent-filter/index.js:155:23)
at /Users/scott/Development/ember-quickstart/node_modules/promise-map-series/index.js:11:14
at tryCatch (/Users/scott/Development/ember-quickstart/node_modules/rsvp/dist/rsvp.js:539:12)
at invokeCallback (/Users/scott/Development/ember-quickstart/node_modules/rsvp/dist/rsvp.js:554:13)
at publish (/Users/scott/Development/ember-quickstart/node_modules/rsvp/dist/rsvp.js:522:7)
at flush (/Users/scott/Development/ember-quickstart/node_modules/rsvp/dist/rsvp.js:2414:5)

ember-cli: 2.13.0-beta.4
http_parser: 2.7.0
node: 7.7.4
v8: 5.5.372.42
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
os: darwin x64
4.1.2

**Comment by rwjblue** [comment]
In general, this should work just fine (and does in many applications). Can you please provide a repo that demonstrates the issue?

**Comment by scottharris86** [comment]
sure heres the basic ember quick start.. very simple.. ive ember installed the scientist-admin which ill link to to next... try ember s and i get the error referenced above.

https://github.com/scottharris86/ember-quickstart.git

and the admin engine is..

https://github.com/scottharris86/scientists-admin.git

maybe im doing something wrong?

**Comment by scottharris86** [comment]
just an update to this... its something with the app folder.. if i delete everything from the app folder and commit and push and reinstall it works.... any ideas why that would be? it doesn't seem like that what i should need to do... 

any help would be appreciated.

thanks

**Comment by majew7** [comment]
Yes @scottharris86, I believe I know why. 

**App directory from an Addon Gets Merged Into the Host.** 
http://ember-engines.com/guide/creating-an-engine

> Observant developers might also note that Addon’s have an app directory in addition to their addon directory. The app directory from an Addon gets merged into the host’s namespace. This allows Addons to “re-export” modules from their own namespace into the namespace of the consumer so that they can be used as if part of the host. Engines, however, should never re-export modules into their host, and so anything placed into the app directory of an Engine Addon will not be included in the build.

**Comment by majew7** [comment]
Since Engines shouldn't re-export, I removed code from the app directory of the Addon, and the `EEXIST: file already exists` compile error went away.

**Comment by scottharris86** [comment]
@majew7 thanks man.. obviously from my comment I discovered the same thing. Just don't understand why the cli puts everything in the app directory if that's not where it's supposed to go. And makes the engine unusable. Appreciate the time and effort. I'm going to close this issue. Really should have done it a while ago

**Comment by majew7** [comment]
> "Just don't understand why the cli puts everything in the app directory if that's not where it's supposed to go."

I think it's because Ember Engines is built on top of an Ember Addon concept, and thus perhaps for other types of Addons (non Engines) it's actually helpful that the CLI puts code in the app folder.  I'm still new to  Ember Addons, so I'm taking an educated guess.

**Comment by majew7** [comment]
@scottharris86, hmmm... I'm questioning my solution to you now. :(

Our team, had decidedto allow files in the Ember Engine `app/` folder to re-export, for unit testing purposes.  When I delete the `app/` files my tests cannot find their subjects! :(

**Comment by villander** [comment]
@majew7 its is a bug of `ember-engines` it should avoid the normal behavior of creating re-export in the `app/`
