### ISSUE TITLE
2nd level bower dependencies are not being loaded properly

### ISSUE THREAD

**Issue by DegreeDev** [ember-engines/ember-engines#412]
We are using [ivy-videojs](https://github.com/IvyApp/ivy-videojs) which is listed as a `dependency` of our engine. This issue is not specific to ivy-videojs but appears to be a larger issue with addons who have bower dependencies inside of engines.

During the build we get this issue: 

    TypeError: Path must be a string. Received undefined
     at assertPath (path.js:7:11)
     at Object.join (path.js:1211:7)
     at Class.included (/Users/mlee/savo-web-host/node_modules/ivy-videojs/index.js:18:27)
     at addons.map.addon (/Users/mlee/savo-web-host/node_modules/ember-cli/lib/models/addon.js:346:34)
     at Array.map (native)
     at Class.eachAddonInvoke (/Users/mlee/savo-web-host/node_modules/ember-cli/lib/models/addon.js:344:24)
     at Class.included (/Users/mlee/savo-web-host/node_modules/ember-cli/lib/models/addon.js:575:10)
     at Class.superWrapper [as included] (/Users/mlee/savo-web-host/node_modules/core-object/lib/assign-properties.js:34:20)
     at Class.included (/Users/mlee/savo-discovery-engine/index.js:9:26)
     at Class.superWrapper [as included] (/Users/mlee/savo-web-host/node_modules/core-object/lib/assign-properties.js:34:20)

This is really just a red herring for a different issue. 

You can see line 18  of [ivy-videojs/index.js](https://github.com/IvyApp/ivy-videojs/blob/master/index.js) is simply: 

     app.import({
        development: path.join(app.bowerDirectory, 'video.js/dist/video-js.css'),
        production:  path.join(app.bowerDirectory, 'video.js/dist/video-js.min.css')
      });

I'm able to locally link and can verify the `app.bowerDirectory` is `undefined`. I am able to simply set the `app.bowerDirectory` to `bower_components` and it builds and functions. I don't think this is great solution as we would have to keep our own versions of all addons who require bower components. 

Has anyone else run into this issue? What have you done to either workaround or solve this? 

Any feedback is appreciated!

Thanks, 

Matthew

edit:

current solution is to update the engines `index.js` included hook to set the bower directory

    //index.js
    const EngineAddon = require('ember-engines/lib/engine-addon');

    module.exports = EngineAddon.extend({
      name: 'savo-discovery-engine',
      lazyLoading: false,
      included(app) {
        this.bowerDirectory = app.bowerDirectory;
        this._super.included.apply(this, arguments);
      }
    });

**Comment by Mukhilan** [comment]
i am running in to the same issue, where engine needs some bower dependencies. But i can't able to import those dependencies in engine-vendor.js. 

Attaching the code & issue i got 

<img width="724" alt="screen shot 2017-09-16 at 10 18 01 pm" src="https://user-images.githubusercontent.com/8384732/30514121-f78082cc-9b2c-11e7-91d4-d2283362e902.png">

<img width="1440" alt="screen shot 2017-09-16 at 10 18 38 pm" src="https://user-images.githubusercontent.com/8384732/30514122-039481e4-9b2d-11e7-8363-a21c0fd8c336.png">

Did you find any workaround to resolve this issue?

**Comment by rwjblue** [comment]
Unfortunately, this is unlikely to be fixed in ember-engines. I would suggest working on migrating those bower dependencies to NPM...

**Comment by Mukhilan** [comment]
Thanks for the suggestion. But after migrating the dependencies to NPM, i ended up in this issue [#303](https://github.com/ember-engines/ember-engines/issues/303)

**Comment by DegreeDev** [comment]
I'm closing this issue as bower will not supported going forward (in general, not just here) with the suggestion to migrate the bower packages to npm/yarn packages. 

Thanks @rwjblue!
