### ISSUE TITLE
Compact re-exports babel plugin causing persistent-cache miss

### ISSUE THREAD

**Issue by stefanpenner** [ember-engines/ember-engines#419]
#408 adds a babel plugin, but does not implement a proper cache key. This results results in warm builds not benefiting from a persistent cache.

more details on how to implement said persistent cache: https://github.com/stefanpenner/broccoli-persistent-filter#persistent-cache

**Comment by stefanpenner** [comment]
cc @trentmwillis

**Comment by rwjblue** [comment]
Caching Was added in https://github.com/ember-engines/babel-plugin-compact-reexports/pull/4, we just need a release.

**Comment by stefanpenner** [comment]
awesome. I'll go wrestle @trentmwillis for release bits for us.

**Comment by trentmwillis** [comment]
Totally thought I had released that...oh well, now y'all have proper privs.
