### ISSUE TITLE
Sharing components from in-repo-addon to in-repo-engine

### ISSUE THREAD

**Issue by buschtoens** [ember-engines/ember-engines#426]
As per the [docs](http://ember-engines.com/guide/sharing-components-and-more) sharing components is possible by moving these components to an addon and then re-exporting these components into the engine's namespace.

As to not have to re-export each and every component manually, ember-engines provides the `EngineAddon` base class.

However, this apparently does not work for in-repo-addons and in-repo-engines.

I've created a [demo repo](https://github.com/buschtoens/in-repo-engine-component-sharing) showcasing the problem.

Even though the in-repo-addon `super-addon` is listed as a dependency in the `super-blog` in-repo-engine's [`package.json`](https://github.com/buschtoens/in-repo-engine-component-sharing/blob/1ba1d7b172dea14fb7dee1b09be2e2f36e4b7412/lib/super-blog/package.json), I still have to [manually re-export ](https://github.com/buschtoens/in-repo-engine-component-sharing/blob/1ba1d7b172dea14fb7dee1b09be2e2f36e4b7412/lib/super-blog/addon/components/foo-bar.js) the [`{{foo-bar}}` component](https://github.com/buschtoens/in-repo-engine-component-sharing/blob/1ba1d7b172dea14fb7dee1b09be2e2f36e4b7412/lib/super-addon/addon/components/foo-bar.js).

Am I doing something wrong or are in-repo-addons just not supported yet?

**Comment by trentmwillis** [comment]
I believe this is just a minor error in the config. In `super-blog` you have:

```json
"paths": [
  "../lib/super-addon"
]
```

Located at `in-repo-engine-component-sharing/blob/master/lib/super-blog/package.json` which would result in `in-repo-engine-component-sharing/blob/master/lib/lib/super-addon`.

I think you want:

```json
"paths": [
  "../super-addon"
]
```

Let us know if that doesn't fix it!

**Comment by buschtoens** [comment]
Wow, I feel silly now. Of course that was the problem! I must have suffered from tunnel vision. Thanks a lot. :heart:
