### ISSUE TITLE
Dependency dedup issue from 0.5.4 -> 0.5.6

### ISSUE THREAD

**Issue by thec0keman** [ember-engines/ember-engines#438]
When upgrading from 0.5.4 -> 0.5.6, our engine's vendor file got a lot larger:
0.5.4
```
 - dist/engines-dist/admin/assets/engine-vendor: 0 B
```

0.5.6
```
 - dist/engines-dist/admin/assets/engine-vendor.js: 157.52 KB (38.49 KB gzipped)
```

There are several dependencies defined in the engine's `package.json`, however none of these are unique to the engine (they are all also defined in the parent app).  Shouldn't these be de-duping?

Ember CLI: 2.13.2
Ember: 2.13.3

**Comment by thec0keman** [comment]
After some further digging, it appears the issue is from [this commit](https://github.com/ember-engines/ember-engines/commit/b16f8553376a13bced4adb73ecf6827de1013d22).  Going to keep digging further to understand what is happening (and if this an issue with our setup).

**Comment by trentmwillis** [comment]
It is likely that the addons being used have custom trees and opting out of the default caching semantics from Ember-CLI. Thus, since we now take into account the caching key, it is no longer being deduped.

**Comment by thec0keman** [comment]
[Here](https://github.com/thec0keman/ember-engine-test/tree/engines-vendor-test) is an example repo.  It is just a basic ember app with an in-repo lazy-loaded engine.  The in-repo engine includes this in its `package.json`:
```
  "dependencies": {
    "ember-data": "*",
    "ember-cli-babel": "*",
    "ember-cli-htmlbars": "*"
  }
```

In 0.5.4 this will build and the engine-vendor file will be 0 bytes.  Checked out to [this commit](https://github.com/ember-engines/ember-engines/commit/b16f8553376a13bced4adb73ecf6827de1013d22), it will include a copy of ember-data in the vendor file.

I do not know very much about broccoli to debug much further, but it appears that `cacheKeyForTree` returns a different cache key for each addon per tree.   So, if I am understanding correctly, this cannot de-dup because the cache keys never match.

**Comment by thec0keman** [comment]
@trentmwillis  sorry I posted before seeing your comment.   Is there something specific about the engine or addon that would opt it out of the default caching?

**Comment by rwjblue** [comment]
The general gist of the caching was proposed in [ember-cli/rfcs#90](https://github.com/ember-cli/rfcs/blob/master/complete/0090-addon-tree-caching.md).  The solution in ember-data would be to implement the `cacheKeyForTree` hook and return a stable value (indicating that its addon tree is not customized per-consumer).

https://github.com/emberjs/data/pull/5110 adds the hook to ember-data.

**Comment by thec0keman** [comment]
Thanks!  That makes sense.  So is the path forward here to submit PR's on each addon that is not being properly cached?
