### ISSUE TITLE
Importing engine as a plain-old addon

### ISSUE THREAD

**Issue by alexander-alvarez** [ember-engines/ember-engines#458]
Before introducing https://github.com/ember-engines/ember-engines/commit/510654690ecd3b679d55f244d07f6e29e888991c we could use engines as regular addons.

For example I have an engine with several routes and components, but I also want to use some of it's components in another addon, so I would import it as you would any other in repo engine.

Now the assumption is that parents of addons are `EngineAddons`, so the above no longer holds true.
Is this a bug? Do we want to support treating engines as regular addons?

**Comment by rwjblue** [comment]
I don't fully understand what you mean here, can you whip up a demo repo that worked prior to that commit and doesn't now so that I can dig in and see whats going on/

**Comment by alexander-alvarez** [comment]
Sorry I seem to have missed this. will throw something up to ilustrate

**Comment by alexander-alvarez** [comment]
Hey @rwjblue I drew up an example illustrating.

:white_check_mark: [working](https://github.com/alexander-alvarez/engines-as-addons-bug/pull/1/files)

:red_circle: [not working](https://github.com/alexander-alvarez/engines-as-addons-bug/pull/2/files)

basically if you try to use an engine as an addon in an addon, and then try to use that addon, the application won't even build because the engine resolution assumes engines are simply within engines.

I don't know if this was intentional or not, but it would be nice to not have to make a 3rd addon for things you want to share between an engine and an addon if it relates to the engine

As an aside there's currently no `0.5.5` `ember-engines` tag in npm.

**Comment by alexander-alvarez** [comment]
@rwjblue does the above clarify what I'm trying to express?

**Comment by alexander-alvarez** [comment]
![image](https://user-images.githubusercontent.com/11779993/29229474-990b3ff8-7eac-11e7-9896-bb6dfe14e017.png)
