### ISSUE TITLE
Merged config.environment files?

### ISSUE THREAD

**Issue by c410-f3r** [ember-engines/ember-engines#459]
In an `addon` <-> `application` relationship, both `config.enviroment `files are merged automatically, does the same happens with the `engine` <-> `application` relationship ?

**myEngine/config/environment.js:**
```
module.exports = function(environment) {
  const ENV = {
    environment: environment,
    modulePrefix: 'myEngine',
    myCustomParameter: 'My custom parameter'
  }
  return ENV;
};
```
**myApp/app/routes/application.js:**
```
import Ember from 'ember';
import config from '../config/environment';

export default Ember.Route.extend({
    init() {
      console.log(config.myCustomParameter);
    }
});

```

Just want to talk with the application, should I use a service instead?

**Comment by mike183** [comment]
Engines receive their own environment config. If you view the page source of an application that includes an engine, you will see an individual meta tag named something like `myEngine/config/environment` which will hold the engines config.

For communicating between an engine and an application you should use a service as you suggested.

Also, just FYI, you will most likely receive help quicker by asking questions in the Ember community slack channel. Github issues is meant for bug reports.

**Comment by c410-f3r** [comment]
Thanks for your reply. I guess there is no way to communicate with the app in a build time manner like config.environment files.
