### ISSUE TITLE
Update existing model data

### ISSUE THREAD

**Issue by dmtask** [ember-engines/ember-engines#460]
Hi,

Briefly something about our structure. We use Ruby on Rails on the server side with the Trailblazer Framework. On client side Ember and Ember Engines.

Now we have the problem that some models are lying in the father, ie the actual Ember app and some models in the engine. Now the models from the engine still have relations to models which are in the father app. If I now want to update data from this model, the engine model works very well, with the relations (which are in the father) he always makes an INSERT and no UPDATE. There is, of course, an error that the entry already exists.

```
ActiveRecord::RecordNotUnique - PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "contacts_pkey"
DETAIL:  Key (id)=(1) already exists.
```

Anyone have an idea how to solve the problem and update the engine model and father model? In the Ember Store, everything is correctly linked and the data is also distributed correctly into the relations. On the server comes the following:

```
Parameters: {"data"=>{"attributes"=>{"patient-number"=>1, "email"=>nil, "employer"=>"", "foreign-doctor"=>"", "family-doctor"=>"", "patient-since"=>"2017-08-02T00:00:00.000Z", "job"=>"", "lab"=>"", "last-therapy"=>"2017-08-02T00:00:00.000Z", "payment-deadline"=>28, "rating"=>1, "recall-type"=>nil, "recommended-by"=>"", "phrophylaxis-user"=>nil, "created-at"=>nil, "updated-at"=>nil, "contact-id"=>nil, "import-id"=>nil}, "relationships"=>{"contact"=>{"data"=>{"type"=>"contacts", "id"=>"1"}}, "customer"=>{"data"=>{"type"=>"customers", "id"=>"1"}}, "patient-insurances"=>{"data"=>[]}, "users"=>{"data"=>[{"type"=>"users", "id"=>"1"}]}, "person"=>{"data"=>{"type"=>"people", "id"=>"1"}}}, "type"=>"patients"}, "id"=>"1", "patient"=>{"data"=>{"attributes"=>{"patient-number"=>1, "email"=>nil, "created-at"=>nil, "updated-at"=>nil}, "relationships"=>{"contact"=>{"data"=>{"type"=>"contacts", "id"=>"1"}}, "person"=>{"data"=>{"type"=>"people", "id"=>"1"}}}, "type"=>"patients"}}}
```

**Comment by knownasilya** [comment]
I think all models have to be in the parent app. The engine can have it's own store with it's own models. Or the Engine could have it's own store, but extend the parent store.

**Comment by dmtask** [comment]
I have the models moved to the core, but same error.

**Comment by knownasilya** [comment]
Did you make the parent's store a dependency of the engine? You need to pass the store to the engine explicitly. See the docs here: http://ember-engines.com/guide/services

**Comment by dmtask** [comment]
Yes i make

**Comment by knownasilya** [comment]
The duplicate key error looks like an error with your backend/database, not with the client.

**Comment by dmtask** [comment]
Yes, that's how it looks. I also do not believe that this is due to Ember. I thought however possibly have the Ember Engines peculiarities, which I have not yet thought.

**Comment by knownasilya** [comment]
Most likely your data isn't matching how you defined the models. Looks like the data is dasherized, while ED usually expects camel cased attributes. I'd ask for help in the slack ember data channel or -help channel, since it's not really an issue with the frameworks.

**Comment by dmtask** [comment]
Ok, thank you for your help :)

**Comment by dmtask** [comment]
The Solution: https://stackoverflow.com/questions/45487326/update-existing-model-data/45563419#45563419
