### ISSUE TITLE
Retry engine on assets error

### ISSUE THREAD

**Issue by josex2r** [ember-engines/ember-engines#471]
Hi.
I don't know if this is really a bug or is the correct implementation but I think I found a cache problem when dealing with the lazy engines.

### How to reproduce the error:
1. Visit an application with a lazy load engine (don't load it yet).
2. In developer tools **enable** the **Offline** mode in the Network panel.
3. Navigate to the lazy engine, the assets _engine.js_ and _engine-vendor.js_ must fail at this point.
4. **Disable** the **Offline** mode.
5. Try to access again to the lazy engine, at this point the engine is inaccesible because the previous errored promise is cached [router-ext.js#L206](https://github.com/ember-engines/ember-engines/blob/master/addon/-private/router-ext.js#L206).

### ¿Why I think the current cache is a bug?
When developing a mobile app the user sometimes can have troubles with its connection, maybe because the wifi is lost or there is not enought network coverage.

To fix the problem I've created a branch named *error-cache* in both [ember-engines](https://github.com/BBVAEngineering/ember-engines/tree/error-cache) and [ember-asset-loader](https://github.com/BBVAEngineering/ember-asset-loader/tree/error-cache) repos (only 2 or 3 commits).
The fix needs changes in 2 repos and I'm not sure if this changes can have side effects, thats why I opened an issue instead a pull-request.

¿What do you think?

**Comment by rwjblue** [comment]
I'm unsure of the exact approach for a fix, but I do agree that this is something that should be possible. I have a few general observations around the changes that you have linked above:

* ember-asset-loader - We shouldn't have to add a new `retry` parameter to the loaders, instead we should (by default) remove the `link` or `script` elements if the loading fails, and likely avoid caching in this scenario also.
* ember-engines - The specific changes here are a bit harder. Assuming we make `ember-asset-loader` not cache failed loads, we would need to also clear failed load promises in the router. However, I do not think an automatic retry system can be our default setup (it needs to be customizable, have an exponential backoff, etc). I think at an app level, it would be better to detect network access is available and retry the previously requested asset loads.  We also need to decide what to do for things like route based lazy engines if you cannot load its assets. We probably already handle this correct, but we should make sure...

**Comment by josex2r** [comment]
About the **ember-asset-loader** there is no problem applying your solution.

On the other hand the changes in **ember-engines** are more complicated.
I've talked with my team mates and they talk about rejecting the current transition if an asset throws an error. This should trigger the default error behaviour in the application.
Could this be possible or we are not heading in the right direction?

**Comment by SergeAstapov** [comment]
Rejecting the current transition if an asset throws an error seems reasonable for route based lazy engines: this would trigger `error` event on router and can be handled by host application.
This approach should give enough flexibility to host app developers to handle retry according to the app requirements.

What can be done with lazy engines mounted in templates via `mount` helper? What can be the way for host route or component (where the engine is mounted) to handle assets loading error and do retry?

**Comment by adrigzr** [comment]
I'm agree with @josex2r on the aproach of using transition reject on transition based engines.

On the other hand, an engine mounted via `mount` helper needs a bit of framework modification. Maybe we can change this helper to export an interface we can use with `with` helper like this:

```
{{#with (mount 'engine') as engine}}
    {{!-- fallback --}}
    {{button action=(action engine.retry)}}
{{/with}}
```

Or, we can turn the helper into a component to fit it on this approach:

```
{{#mount 'engine' as engine}}
    {{!-- fallback --}}
    {{button action=(action engine.retry)}}
{{/mount}}
```

Inside the block we can print the fallback of the failed engine as a retry button with a contextual action.

What do you think?

**Comment by rwjblue** [comment]
`{{mount` is a completely different story 😸, we do not currently support an out of the box way to do lazy routeless engines so we shouldn't complicate this discussion with that topic.  See https://github.com/ember-engines/ember-asset-loader/issues/56 for a good place to discuss that though.

---

@josex2r 

> they talk about rejecting the current transition if an asset throws an error. This should trigger the default error behaviour in the application.

Yes, totally agreed here. The only "trick" here would be to ensure that the route loading promise is not cached as a rejected promise.

**Comment by trentmwillis** [comment]
I'm :+1: on the ember-asset-loader changes. @josex2r, if you open a PR, I'd be happy to review.

As for the ember-engines side of things, I think an asset load failure should propagate like any other route transition failure (seems like we have an agreement in this area). We could internally track those asset load failures and keep a reference to the error object that allows the load to be retried, but what is unclear to me is what sort of API we would expose to allow consumers control over the reload behavior.

**Comment by josex2r** [comment]
Then I'm going to start making some changes, I hope to have news soon.
Thanks for your help :)

**Comment by trentmwillis** [comment]
The ember-asset-loader changes have landed, but there is still work to be done in ember-engines itself.
