### ISSUE TITLE
Minimatch 2.0.10 Node Security Vulnerability

### ISSUE THREAD

**Issue by jacefarm** [ember-engines/ember-engines#472]
We're taking Engines for a spin, and we've been alerted to a [Node Security Vulnerability](https://nodesecurity.io/advisories/118).

The dependency lineage is thus:

```
Vulnerable: <=3.0.1 - Patched: >=3.0.2 - Path: ember-engines@0.5.12 > broccoli-babel-transpiler@5.7.2 > babel-core@5.8.38 > minimatch@2.0.10
```

But following the trail, I see no explicit reference to minimatch (babel-core?).  However, the yarn.lock file has references that would not bump to the suggested `v3.0.2` remedial version for minimatch.

**Comment by mike183** [comment]
@rwjblue Am I correct in thinking that this is fixed on master?

**Comment by rwjblue** [comment]
Yes, should have been fixed by https://github.com/ember-engines/ember-engines/commit/a75e8fde1a5d2b77541c703c7be6b1f5e449bd8c.
