### ISSUE TITLE
Link into host app from engine

### ISSUE THREAD

**Issue by badmacstone** [ember-engines/ember-engines#475]
Hi there. Is it possible to `link-to` from an engine into the host app?

Host app:
```
this.mount('accounting', { as: 'accounting', path: 'accounting' });

this.route('dashboard');
```

Engine:
```
{{#link-to "dashboard"}} Dashboard {{/link-to}}
```

This results in this route: `/accounting/dashoard`. But what I want is `/dashboard`.

**Comment by mike183** [comment]
See the guides on external links, http://ember-engines.com/guide/linking-and-external-links

**Comment by badmacstone** [comment]
Oh thanks. The word "external" made me thought that it is about links to oustide the app.

**Comment by trentmwillis** [comment]
@badmacstone yeah, naming that feature was difficult, if you have any alternatives the RFC is (technically) still open: https://github.com/emberjs/rfcs/pull/122
