### ISSUE TITLE
Testing engine component with app service injection

### ISSUE THREAD

**Issue by garno** [ember-engines/ember-engines#476]
Hi,

I’ve been working on my first Ember app using engines and I’m having an issue with my test suite. I hope you’ll be able to help me out :)

Here’s what I have, [I’ve reduced the issue to the smallest reproducible case in a small app](https://github.com/garno/ember-engine-service-test):

- A simple service `app/services/my-global-service.js`
- An engine `lib/my-engine`
- A component within my engine `lib/my-engine/addon/components/my-engine-component.js`

The component need the service to compute a property so it’s added to the engine dependencies and injected into the component.

```js
// Vendor
import Ember from 'ember';

const {computed, inject} = Ember;

export default Ember.Component.extend({
  myGlobalService: inject.service('my-global-service'),

  testMethod: computed(function() {
    return this.get('myGlobalService').fakeMethod();
  })
});
```

To test the component, I use the `engineResolverFor` method [as described in the README.md](https://github.com/ember-engines/ember-engines#unitintegration-testing-for-in-repo-engines) but I can’t figure out how to specify that this component `needs` the service.

As per previous experiences, I should do something like that:

```js
setupComponentTest('my-engine-component', {
  resolver: engineResolverFor('my-engine'),
  needs: ['service:my-global-service'],
  unit: true
});
```

But, unfortunately I can’t make it works. The factory seems to be unknown to the engine resolver. 

```
Attempting to register an unknown factory: 'service:my-global-service'
```

Any idea what I’m missing? Any help would be appreciated :) The sample application I’ve provided at the beginning should demonstrate the issue. Just run the tests.

Thanks,

Sam

**Comment by garno** [comment]
I've though about it over lunch and realized I might as well stub my services. With that in mind, here’s the code that worked for me. If anyone else was wondering how to achieve that.

```js
// Vendor
import Ember from 'ember';
import engineResolverFor from 'ember-engines/test-support/engine-resolver-for';
import {describe, it} from 'mocha';
import {setupComponentTest, setupTest} from 'ember-mocha';
import chai from 'chai';

const {expect} = chai;

const engineResolver = engineResolverFor('my-engine');

describe('Unit | Components | my-engine-component', () => {
  setupComponentTest('my-engine-component', {
    resolver: engineResolverFor('my-engine'),
    unit: true
  });

  const globalServiceStub = Ember.Service.extend({
    fakeMethod() {
      return true;
    }
  });

  beforeEach(function() {
    this.register('service:my-global-service', globalServiceStub);
  });

  describe('testMethod', () => {
    it('should return true', function() {
      const component = this.subject();

      return expect(component.get('testMethod')).to.equal(true);
    });
  });
});
```

**Comment by ShaharAvigezer** [comment]
hi @garno I had the same issue and you just saved me so much time! thank you 🙏
