### ISSUE TITLE
Update README with longhand lazyLoading syntax

### ISSUE THREAD

**Issue by GCheung55** [ember-engines/ember-engines#487]
Per slack convo:

>garrick [8:39 AM] 
>I’m seeing two ways to define `lazyLoading` an an engine’s `index.js` file. Which is the right way? `lazyLoading: true` or `lazyLoading: {enabled: true}`?
>
>mike183 [9:30 AM] 
>garrick The first is shorthand for the second
>
>garrick [10:02 AM] 
>I see. I was a little confused with seeing the shorthand in the guide and read me but the longhand form in the generated `index.js` file. Perhaps the guide, readme, and blueprint should align? Does it make sense to file an issue for this?
>
>rwjblue [10:26 AM] 
>Would love a PR but an issue seems like a good start :blush:
>
>garrick [10:31 AM] 
>Okay, I’ll file an issue to discuss in which direction, use shorthand or longhand… unless you wanna just tell me which way to go. :slightly_smiling_face:
>
>rwjblue [10:35 AM] 
>I think we should only reference the object version
>Support for the Boolean is mostly legacy
>And could eventually be deprecated

ember-engines.com should also be updated.

**Comment by trentmwillis** [comment]
The necessary documentation updates have been made.
