### ISSUE TITLE
Update README to include details for testing lazy engines

### ISSUE THREAD

**Issue by amk221** [ember-engines/ember-engines#496]
The docs currently explain how to test engines by setting a custom resolver:

https://github.com/ember-engines/ember-engines#unitintegration-testing-for-in-repo-engines

^ This works great for non-lazy engines.

However, if the engine is lazy the tests don't pass because the engine is not loaded.

Please could the docs be updated to explain how to do this?

**Comment by denzo** [comment]
@amk221 the workaround that worked for us was to include the `<script>` tags manually on the `tests/index.html` pointing to the engine bundle.

**Comment by bertdeblock** [comment]
This is now covered here: https://ember-engines.com/docs/testing-acceptance#lazy-engines, so I think this issue can be closed?
