### ISSUE TITLE
Cannot import anonymous AMD assets in lazy engine

### ISSUE THREAD

**Issue by gschulze** [ember-engines/ember-engines#499]
Importing anonymous AMD assets inside lazy engines does not work:

`this.import('vendor/heatmap.js', { using: [ { transformation: 'amd', as: 'heatmap.js' } ] })`

results in the following error:

`TypeError: Cannot read property 'has' of undefined`

A debug session revealed that `this._customTransformsMap` is `undefined` when the import function is called from the engine addon. Replacing `this.import(...)` with `app.import(...)` resolves the problem, but results in the asset being hoisted into the host application.

**Comment by tony2n2** [comment]
`define.amd` is undefined when engine is set to lazy.

**Comment by XaserAcheron** [comment]
Ouch -- just ran face-first into this while doing some long-awaited updates. Seemed this worked fine on older Ember versions, but v3.1.x throws exactly the error as described.

**Comment by aaxelb** [comment]
FYI, this is fixed for ember-cli 3.1 by #562, but I don't know if it'll be merged because it doesn't work with ember-cli master.
