### ISSUE TITLE
avoidable funnels + merges

### ISSUE THREAD

**Issue by stefanpenner** [ember-engines/ember-engines#508]
https://github.com/ember-engines/ember-engines/blob/8f66b5e3b8089cd53884be49f270cac05f9a3d17/lib/engine-addon.js#L319

is often truthy, when it really isn't needed as `maybeMergeTrees` via `ember-cli/broccoli/merge-trees` will return EMPTY_MERGE_TREES. In this location this internal construct leaks out, and results an un-needed funnel.

This optimization "EMPTY_MERGE_TREES" should likely be made to not leak as it does, but likely a short-term fix is to make `maybeMergeTrees` aware of it, so that downstream code can be made aware.

- [ ] fix
- [ ] see impact (should often-times remove 1 funnel and 1 merge per engine)
- [ ] @rwjblue thoughts?

**Comment by rwjblue** [comment]
`maybeMergeTrees` is not the one from ember-cli, it does not return the `EMPTY_MERGE_TREE` constant.

The `maybeMergeTrees` used is here:

https://github.com/ember-engines/ember-engines/blob/8f66b5e3b8089cd53884be49f270cac05f9a3d17/lib/engine-addon.js#L297-L304

And it definitely allows for returning `undefined`.

**Comment by stefanpenner** [comment]
@rwjblue actually, that isn't the `mergeTrees` you expect. It's actually this one: https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/merge-trees.js Which returns EMPTY_MERGE_TREE here https://github.com/ember-cli/ember-cli/blob/master/lib/broccoli/merge-trees.js#L77

**Comment by stefanpenner** [comment]
There are actually additional places such as:

https://github.com/ember-engines/ember-engines/blob/8f66b5e3b8089cd53884be49f270cac05f9a3d17/lib/engine-addon.js#L158-L166
which encounter these `EMPTY_MERGE_TREE`

**Comment by stefanpenner** [comment]
These two trees can also be `EMPTY_MERGE_TREE`'s https://github.com/ember-engines/ember-engines/blob/8f66b5e3b8089cd53884be49f270cac05f9a3d17/lib/engine-addon.js#L822-L823

Which would then result in the following `funnel` and `compileLazyEngineStyles` being potentially avoidable (or fast-pathed): 

```
var externalTree = new Funnel(vendorTree, {
          srcDir: 'vendor',
          destDir: 'vendor',
          allowEmpty: true,
        });

        var finalStylesTree = this.compileLazyEngineStyles(
          vendorTree,
          externalTree
        );
```

**Comment by stefanpenner** [comment]
Skimming it looks like quite abit of avoidable work happens in engine builds when they encounter these empty trees. This is likely a good source of perf if addressed.

**Comment by rwjblue** [comment]
Ya, confirm I had thought we were using `broccoli-merge-tree` directly.  I completely forgot that we used ember-cli's internal / private one...
