### ISSUE TITLE
Request: Support Ember 2.18.x

### ISSUE THREAD

**Issue by JHKennedy4** [ember-engines/ember-engines#514]
Just upgraded our app from Ember 2.14 to Ember 2.18, and I'm seeing the following.

```
Uncaught Error: Could not find module `@ember/routing/route` imported from 'file/in/engine';
```

I'm realizing now that the latest release only supports up to Ember 2.12.

Is there a timeline for releasing a version compatible with the latest Ember?

**Comment by mike183** [comment]
I'm currently using engines with Ember v2.17 without issues, though I haven't had the chance to upgrade and try it out with Ember v2.18 yet.

**Comment by knownasilya** [comment]
Updating to the latest version of ember-cli-babel might help.

**Comment by JHKennedy4** [comment]
The issue really seems to be limited to that module, and only inside the Engine.

Also, just realizing that Ember 2.18 only landed on the 1st, so totally understand if support isn't quite there yet.

It's also still possible this is all our fault...

**Comment by JHKennedy4** [comment]
It was our fault. Error went away when we finally made it through the last of the linter errors. Still not sure why it was showing up only in the engine, but oh well.
