### ISSUE TITLE
App's Instance Initializers are executed for each engine loaded.

### ISSUE THREAD

**Issue by selvaa89** [ember-engines/ember-engines#517]
Problem: Instance initializers from app's dependencies are executed once on the app instance and again for engine instance even though engine is not depending them. Can the second execution be avoided?

My app has a non lazy loaded engine.

My app uses ember-simple-auth for authentication. While trying to optimize the loading/initial rendering rendering time, I found that the instance initializer 'setup-session-restoration' is executed once for the app and again for the engine.

Is it intentional? I don't understand because, the engine doesn't depend on ember-simple-auth and it is not lazy loaded.

**Comment by rwjblue** [comment]
Seems like a bug, but a reproduction would make it much easier to track down and fix...

**Comment by selvaa89** [comment]
After debugging, I found that one of the dependencies of the engine was depending on the ember-simple-auth. So, executing the initializer is the expected behavior.

Hence closing the issue.
