### ISSUE TITLE
What is the roadmap? future?

### ISSUE THREAD

**Issue by villander** [ember-engines/ember-engines#522]
Is Ember engines beta? or do we already have a release candidate?

What is the roadmap?

We have several incompatibility with the current state of the ecosystem ember cli + ember-engines. I would like to help a lot, but I need ember-engines to become more public

**Comment by villander** [comment]
@trentmwillis @stefanpenner @rwjblue

**Comment by nightire** [comment]
it would be great if you can join slack community, there's an active channel for ember-engines.

https://ember-community-slackin.herokuapp.com/

**Comment by villander** [comment]
@nightire I'm very active in Ember's slack, and I already asked that question there, but I did not get answers. ¯\_(ツ)_/¯

**Comment by mike183** [comment]
As I understand, ember-engines is currently pre-beta, though there are many large companies such as LinkedIn using it in production with success.

I also agree that it would be good to get some clarification on what work is required (if any) to push ember-engines towards a 1.0 release.

WRT incompatibilities, I'm currently using ember-engines with Ember/EmberCLI v2.18 and have not seen any issues.

**Comment by josemarluedke** [comment]
I also would like to Ember Engines in a state where we could say it is not beta anymore.

As for incompatibilities, I think the major one is with FastBoot. We had a strong use case for Ember Engines, but being incompatible with FastBoot was a deal breaker.

**Comment by villander** [comment]
@mike183 I say incompatibility for example with Fastboot and mainly with Ember's ecosystem of tests, it's just to look at issues.

I think that with the issues of improvements and features that this repo already has, it would have to push ember-engines to 1.0. We who use ember-engines in production want very mature this project, route-less until today has not been implemented for example. But we need the support or release of the core team to work on it

**Comment by villander** [comment]
I think the priorities would be to add support for Fastboot #444  and improve compatibility with the Ember testing API.

After that, attack things like:

- Lazy loading for route-less Engines

- Loading engines at runtime

- And several other interesting issues that were opened

**Comment by mike183** [comment]
FYI, https://discuss.emberjs.com/t/readers-questions-what-is-the-status-of-ember-engines/14236

**Comment by villander** [comment]
Yes, I read that. It was great to have this answer, I think we can close this issue work hard for the growth of embe-engines.

I'm excited about what's coming.
