### ISSUE TITLE
Support for new test syntax

### ISSUE THREAD

**Issue by mydea** [ember-engines/ember-engines#525]
Has anyone got integration tests working for their (lazy) engine, with the new test syntax?

I get the error that `xxxx is not a helper`. I guess it is because `setApplication` sets the dummy app, in which the components themselves are not directly registered?

I somehow got it to work with this pretty hacky code:

```js
import Resolver from '../../resolver';
import { setResolver } from '@ember/test-helpers';

const modulePrefix = 'my-engine-name';
const resolver = Resolver.create();

export default function setupResolver(hooks) {
  // Manually fix the entries for the engines so they can be found by the resolver
  // Put everything from the my-engine-name namespace into dummy as well
  // E.g. my-engine-name/components/my-component becomes dummy/components/my-component
  let modules = resolver._moduleRegistry._entries;

  let newModules = {};
  let overwriteModules = {};
  let originalModules = {};

  Object.keys(modules).forEach((module) => {
    if (module.startsWith(modulePrefix)) {
      let newName = `dummy/${module.substr(modulePrefix.length + 1)}`;

      if (!modules[newName]) {
        newModules[newName] = modules[module];
      } else {
        originalModules[newName] = modules[module];
        overwriteModules[newName] = modules[module];
      }
    }
  });

  hooks.beforeEach(function() {
    Object.keys(newModules).forEach((module) => {
      modules[module] = newModules[module];
    });
    Object.keys(overwriteModules).forEach((module) => {
      modules[module] = overwriteModules[module];
    });
  });

  hooks.afterEach(function() {
    Object.keys(newModules).forEach((module) => {
      delete modules[module];
    });
    Object.keys(overwriteModules).forEach((module) => {
      modules[module] = originalModules[module];
    });
  });

  return setResolver(resolver);
}
```

and then, in my integration tests:

```js
import { module, test } from 'qunit';
import { setupRenderingTest } from 'ember-qunit';
import setResolver from 'dummy/tests/helpers/set-resolver';
// ... other dependencies

module('Integration | Component | my test component', function(hooks) {
  setupRenderingTest(hooks);
  setResolver(hooks);

  // actual tests go here
});
```

I'm sure there is a better way, but I'm not sure what it is ;)

**Comment by mydea** [comment]
I also seem to be unable to overwrite the store service in integration tests in the engine. E.g. this doesn't work, the store service is always the 'real' store service:

```js
const storeService = Service.extend({
  // my mock service
});

module('Integration | Component | my-component', function(hooks) {
  setupRenderingTest(hooks);
  setResolver(hooks);

  hooks.beforeEach(function() {
    this.owner.register('service:store', storeService);
    this.store = this.owner.lookup('service:store');
  });

  // ...

});
```

**Comment by crhayes** [comment]
@mydea I'm having the same issue mocking the store in my app (non-engine) integration tests. I am on Ember 2.18.

Have you been able to replicate this issue inside your main app?

**Comment by mydea** [comment]
Haven't tried this, as our main app is very small and most stuff happens in engines.

**Comment by omarhamdan** [comment]
This setup worked for me:

```js
// engine-name/integration/a-component-test.js

import { module, test } from 'qunit';
import engineResolverFor from 'ember-engines/test-support/engine-resolver-for';
import { setupRenderingTest } from 'ember-qunit';
import { setResolver, setApplication } from '@ember/test-helpers';

module('Integration | Component | a component', function(hooks) {
  setupRenderingTest(hooks);
  setApplication(null);
  setResolver(engineResolverFor('engine-name'));

  test('It shows correct placeholder', async function() {
    ...
  });
});


// Since the engine is lazy loaded we preload the assets. 
// We used ember-asset-loader.

// In tests/test-helper.js

import Application from '../app';
import config from '../config/environment';
import { setApplication } from '@ember/test-helpers';
import { start } from 'ember-qunit';
import preloadAssets from 'ember-asset-loader/test-support/preload-assets';
import manifest from 'simon/config/asset-manifest';

setApplication(Application.create(config.APP));
preloadAssets(manifest).then(start);
```
Hope this helps!

**Comment by lennyburdette** [comment]
I solved this a slightly different way—I default to using the engines resolver, but set the application as the dummy app for acceptance tests:

https://discuss.emberjs.com/t/testing-engines-with-ember-qunit-3-4/14653

**Comment by bartsqueezy** [comment]
Ran into this same problem.  Not a lot of documentation on this, unfortunately, but was able to find [a nice example on how to set a custom resolver during an integration test using the new testing syntax](https://github.com/rwjblue/ember-qunit-codemod/pull/59/files#diff-73cc0ae3b7afa920e08ff5b5c80f3e03).  Props to @rwjblue for having a good test example to show this 👍 

In short, you can do this (using mocha in example)...

```js
const resolver = engineResolverFor('appointments-manager');

describe('Integration | Component | Date picker', () => {
  setupRenderingTest({ resolver });

  test('renders text', async function(assert) {
    await render(hbs`{{date-picker}}`);
    // expect something
  });
});
```

Hope this helps answer some questions!

**Comment by mydea** [comment]
This is definitely nice! But still lead to some issues.
For example, some services that are passed into the engine as a dependency are not present in that case - But it is rather easy to manually inject them, so that's fine.

Also, I got an error that "link-to-external" is not set.

Finally, there is also an issue with the config: It will then load the engine config, which is especially problematic e.g. with ember-basic-dropdown. It uses code like this:

```js
let config = getOwner(this).resolveRegistration('config:environment');
if (config.environment === 'test') {
  // ...
}
```

Here, it would report environment ='development' for me, which breaks everything.

So I ended up with a custom helper that looks something like this:

```js
import engineResolverFor from 'ember-engines/test-support/engine-resolver-for';
import { setupRenderingTest } from 'ember-qunit';
import Service from '@ember/service';
import LinkToExternalComponent from 'ember-engines/components/link-to-external-component';
import { set } from '@ember/object';

const modulePrefix = 'my-engine';
const resolver = engineResolverFor(modulePrefix);

const AssetMapService = Service.extend();

export function setupIntegrationTest(hooks) {
  setupRenderingTest(hooks, { resolver });

  hooks.beforeEach(function() {
    // Add services that are not picked up by default
    this.owner.register('service:asset-map', AssetMapService);

    let config = this.owner.resolveRegistration('config:environment');
    set(config, 'environment', 'test');

    this.owner.register('component:link-to-external', LinkToExternalComponent);
  });
}
```

Which I use _instead_ of the normal `setupRenderingContext(hooks)` function in my integration test.

**Comment by buschtoens** [comment]
The solution provided by @mydea (thanks!) only seems to work for *non-lazy loading* engines, which is probably because in a render test there is no application booting and thus no `asset-loader` service loading the extra assets.

**Comment by mydea** [comment]
This part is rather straight forward to solve, by adapting your test-helpers.js as described here https://github.com/ember-engines/ember-engines#testing-for-standalone-engines

**Comment by buschtoens** [comment]
I was just about to paste this code:

```
import Application from '../app';
import config from '../config/environment';
import { setApplication } from '@ember/test-helpers';
import { start } from 'ember-qunit';
import preloadAssets from 'ember-asset-loader/test-support/preload-assets';
import manifest from 'dummy/config/asset-manifest';

preloadAssets(manifest);
setApplication(Application.create(config.APP));

start();
```

Didn't know that this is a promise, thanks!

**Comment by SergeAstapov** [comment]
Once we upgraded Ember Data and Ember.js to 3.16, using `setupTest(hooks, { resolver });` approach in engine unit/rendering tests results in deprecation message being triggered by Ember Data:
```
This test relies on a deprecated test setup that is no longer supported by EmberData. To resolve this you will need to be on a recent version of @ember/test-helpers AND your tests must use `setApplication()` instead of `setResolver()` and `module()` with `setup*Test()`instead of `moduleFor*()`. [deprecation id: ember-data:legacy-test-helper-support]
```

triggered from here https://github.com/emberjs/data/blob/85dbc55e7989157307ab897ac0b126bd777a724b/packages/-ember-data/addon/setup-container.js#L13

Looking into what happens when `resolver` is provided to `setupTest`, looks like it cases `buildOwner` function to use `legacyBuildRegistry` function:

https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/setup-context.ts#L197
https://github.com/emberjs/ember-test-helpers/blob/master/addon-test-support/%40ember/test-helpers/build-owner.ts#L54

Looks like with new Ember versions using the approach suggested in [above comment](https://github.com/ember-engines/ember-engines/issues/525#issuecomment-402131973) is not gonna work moving forward and we need to find a new solution that would work with New Testing Style helpers (which should happen with #653).

**Comment by rwjblue** [comment]
Confirm, #653 is the path forward here.

**Comment by lougreenwood** [comment]
It seems that this solution breaks the usage of `ember-cli-mirage` in integration tests in an engine.

What I currently believe is happening in:

- `e-c-m` registered it's config in an [initialiser](https://github.com/miragejs/ember-cli-mirage/blob/ba5ef278a5daa8971ab20a6210f383774d1281ca/app/initializers/ember-cli-mirage.js#L16)
- the initialiser runs on test start, before `setupRenderingTest(hooks, resolver)`
- `setupMirage(hooks)` is run after we `setupRenderingTest` with the engine-specific resolver (or whatever it is 😃).
- `startMirage` [attempts to fetch the config which was registered in the initialiser](https://github.com/miragejs/ember-cli-mirage/blob/ba5ef278a5daa8971ab20a6210f383774d1281ca/addon/start-mirage.js#L27)
- But because we switched the resolver after mirage registered the config, we can't resolve the registrations from the owner/application registry, because it's different...
