### ISSUE TITLE
FOUC in lazy engines + fastboot

### ISSUE THREAD

**Issue by Duder-onomy** [ember-engines/ember-engines#530]
Using version 0.5.16, and the nearly latest fastboot 1.1.3
There is a FOUC when a lazy engines routes is being served by fastboot. 

The engine.css is not loaded until after ember boots and revives the page:
![image](https://user-images.githubusercontent.com/1612785/37999147-644e29e6-31d6-11e8-986e-34b58489f552.png)

It would be nice to get that engine.css injected into the head when rending a lazy engine.

I also opened an issue in the fastboot repo to improve visibility.
https://github.com/ember-fastboot/ember-cli-fastboot/issues/590

**Comment by catz** [comment]
Also very interested in fastboot+lazy engines, but couldn't figure out on how to wrap engine-vendor.js file in fastbootTransform. Tried to do like this https://github.com/catz/ember-engines-demo-fb/blob/master/lib/viewer/index.js without luck. It doesn't work when lazyloading=true, but works when false.

If I wrap this line in fastbootTransform() https://github.com/ember-engines/ember-engines/blob/a971c9ce3d0144ea8c4b82f9e98c2c568dd0ec9e/lib/engine-addon.js#L930 I get normal wrapping but it would be cool to have some hook to do this.

Please share your thoughts. Thanks in advance.

**Comment by villander** [comment]
> Also very interested in fastboot+lazy engines, but couldn't figure out on how to wrap engine-vendor.js file in fastbootTransform. Tried to do like this https://github.com/catz/ember-engines-demo-fb/blob/master/lib/viewer/index.js without luck. It doesn't work when lazyloading=true, but works when false.

@catz `fastbootTransform` just avoid your tree of be import on node environment. So this, is not a solution.

@Duder-onomy here we guarantee that all vendor is loaded in fastboot sandbox, its seems like a fastboot bug than from ember-engines.

**Comment by catz** [comment]
@villander 

>fastbootTransform just avoid your tree of be import on node environment. 

Maybe I didn't understand you. This is exactly what I want and did not find on how to do it for lazy vendor files.

**Comment by catz** [comment]
@villander 

sorry, but line you mentioned doesn't explain that code loaded in fastboot sandbox. one little example

```
  included() {
    this._super.included.apply(this, arguments);
    this.import('vendor/test.js');
  }
```

and one line in test.js - console.log(window.location.hostname);

when I run my server in fb mode I get

```
TypeError: Cannot read property 'hostname' of undefined
    at /Users/catz/Projects/app/frontend/tmp/broccoli_merge_trees-output_path-nJuVzILF.tmp/engines-dist/wall/assets/vendor/test.js:1:1
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at VMSandbox.eval (/Users/catz/Projects/app/frontend/node_modules/fastboot/src/vm-sandbox.js:14:16)
    at /Users/catz/Projects/app/frontend/node_modules/fastboot/src/ember-app.js:156:15
```

I suppose if it would be wrapped in fb transform, I didn't get this error ?

**Comment by Duder-onomy** [comment]
@catz I am not sure why you are having an error... Since #494 landed everything is working fine for me. The fastboot transform essentially skips any code you put through it during fastboot. It is a quick fix for fastboot issues, but I think most of the time you will want to manually fix your code to make it work as best it can in fastboot. Following the ember-engines docs, and making sure you are on the latest fastboot and ember-engines versions should work fine. You might want to try the fastboot channel in the ember slack, everyone there is super nice and responsive. 

This issue is about a FlashOfUnstyledContent, in the sense that the ember-app is not loading the lazy-engines css until ember has booted. 

Thanks @villander, I will close this one for now and try to poke the corresponding issue on the fastboot repo.

**Comment by Duder-onomy** [comment]
AIGHT! I think I found the spot to properly push on this one. 

Ember asset loader, This function does nothing during fastboot for engines... 
https://github.com/ember-engines/ember-asset-loader/blob/master/addon/loaders/utilities.js#L33
