### ISSUE TITLE
0.5.18 has environment regression

### ISSUE THREAD

**Issue by kellyselden** [ember-engines/ember-engines#537]
https://github.com/yapplabs/ember-modal-dialog/blob/db5778b23d7fd3de66811fcce9d6001f5c539d8a/app/services/modal-dialog.js#L23 stopped working after 0.5.15. In 0.5.14, `ENV.environment` is correctly `test`. After updating to >= 0.5.15, `ENV.environment` is `undefined` for the same test.

**Comment by villander** [comment]
@kellyselden you can reproduce this error in a public repo? So I can help you better

**Comment by kellyselden** [comment]
Here's a start https://github.com/kellyselden/engine-modal-bug. It only fails at localhost:4200/tests. If you run `ember test`, it passes. If you pin ember-engines to 0.5.14, the tests start passing in both command line and browser.

**Comment by villander** [comment]
@kellyselden I fixed this with #538 and tested with https://github.com/kellyselden/engine-modal-bug

You can test this branch with your current project?

**Comment by Penthious** [comment]
@villander this issue reappeared itself in 0.5.21 and is still in 2.5.24. When I try 0.5.20 my ENV.enviroment shows up in production but when I upgrade my version ENV.environment is undefined.

**Comment by villander** [comment]
@Penthious can you replicate this on a public repo? please

**Comment by villander** [comment]
@Penthious @kellyselden this issue are fixed on `0.6.x`

@stefanpenner @dgeb can you close this, please.

**Comment by dgeb** [comment]
@villander thanks for following up.

If anyone has a reproduction that still fails in 0.6.x, please let us know.
