### ISSUE TITLE
Deprecation warning for replaceWithExternal/transitionToExternal

### ISSUE THREAD

**Issue by mydea** [ember-engines/ember-engines#558]
When using `this.transitionToExternal` in an engine route, a deprecation warning is output:

```
DEPRECATION: Route#router is an intimate API that has been renamed to Route#_router. 
However you might want to consider using the router service
[deprecation id: ember-routing.route-router] 
See https://emberjs.com/deprecations/v3.x#toc_ember-routing-route-router for more details.
```

Originating here: https://github.com/ember-engines/ember-engines/blob/aeea4be21bce87d60e1aa3b03e38a4ecb69cb26b/addon/-private/route-ext.js#L10

**Comment by SergeAstapov** [comment]
This is valid for Ember => 3.1

Would be nice to replace `this.router` with `getOwner(this).lookup('service:router')`.
But then we would need to provide the instance of RouterService from host app 🤔

Any ideas how to prevent explicitly defining `RouterService` in `dependencies.services` within engine.js file?

**Comment by rwjblue** [comment]
We can (for now) swap to `let router = this._routerMicrolib || this.router; router[methodName](...stuff)`, but I agree that we do need to work to swap to the public service...

**Comment by buschtoens** [comment]
Aaaaaand, it's gone. 😄 

https://github.com/emberjs/ember.js/commit/50a5a5df8172acbe6d287b1ba74b44485802eced#diff-7e252e0880a2b1de772cbcabaf3ddfb4L121

`router` has now been renamed to `_router` and it's breaking with Ember 3.6.

> We can (for now) swap to `let router = this._routerMicrolib || this.router; router[methodName](...stuff)`, but I agree that we do need to work to swap to the public service...

I think that does not work. We're talking about the `Route` here, not the `Router`. I'll send a PR to hot fix as

```js
return (this._router || this.router)[methodName](externalRoute, ...args);
```
