### ISSUE TITLE
drop useDeprecatedIncorrectCSSProcessing

### ISSUE THREAD

**Issue by stefanpenner** [ember-engines/ember-engines#559]
cc @rwjblue we are good to drop this right?

**Comment by rwjblue** [comment]
ya, just need to verify we don't need it any longer in any of our apps, then we can bump to `0.6.0` and drop...

**Comment by stefanpenner** [comment]
likely a 0.4.x release eh?

**Comment by rwjblue** [comment]
Not sure I understand. We are already on 0.5, I would think this would require a 0.6.0 (e.g. a breaking change)...

**Comment by stefanpenner** [comment]
@rwjblue oops, you are right. 0.6.x
