### ISSUE TITLE
Does in-repo engines support lazy loading.

### ISSUE THREAD

**Issue by avacado** [ember-engines/ember-engines#563]
I am creating an in-repo engine(basically addon) and set following in the index.js
lazyLoading: {
    enabled: true
  },

When I run my app in production, I get the error about route not found on undefined. The issue doesn't occur in mirage-setup OR if I disable the lazyloading. 

Has anyone seen this issue and possible workaround

**Comment by catz** [comment]
Hello, can you prepare minimal example repo? Can you check mine small example https://github.com/catz/eng-test ?

**Comment by stefanpenner** [comment]
Ya it should work, our apps use this.

If you can provide a reproduction I'll, reopen :)
