### ISSUE TITLE
transitionToExternalRoute for controller

### ISSUE THREAD

**Issue by roberkules** [ember-engines/ember-engines#590]
Hi,

so there's `transitionToExternal` on the _route_, but no equivalent for the _controller_ (something like `transitionToExternalRoute` as a counterpart to `transitionToRoute`).

how am I supposed to transition to an external route from the controller, or am I missing something?

thx, robert

**Comment by mike183** [comment]
Looks like this has just never been implemented. Unless it was left out for a specific reason?

If not, I guess we'd need something similar to [this](https://github.com/ember-engines/ember-engines/blob/8b3c57fffaaaac21b4f76aa9362de36a81782bb8/addon/-private/route-ext.js), but for controllers.

@rwjblue c/d?

**Comment by buschtoens** [comment]
This is probably best consolidated into #587?

**Comment by villander** [comment]
Will be fixed by #697

**Comment by bertdeblock** [comment]
Can we close this?
