### ISSUE TITLE
queryParams not work when call transitionToExternal

### ISSUE THREAD

**Issue by jizhu** [ember-engines/ember-engines#602]
https://github.com/ember-engines/ember-engines/blob/8b3c57fffaaaac21b4f76aa9362de36a81782bb8/addon/-private/route-ext.js#L7

Hi, 

When I call this.transitionToExternal('error', { queryParams: { trk: 'lalal'}});, it does jump to error route, but without params I set.
No errors in console.

I set the external Routes in engine.js
 externalRoutes: [
      'error',
    ],

Does anyone know this situation.

**Comment by mastastealth** [comment]
@jizhu Do you recall the solution? :sweat_smile:
