### ISSUE TITLE
PatternLibrarys and Component-Sharing

### ISSUE THREAD

**Issue by Haidy777** [ember-engines/ember-engines#603]
I've read through a bunch of Issues and also dug through the guides and I can't find a definite answer.

We've got a pretty big EmberApp, so we thought we could split it up into engines (as not every User needs every Part of the App). We implemented a lot of our components inside a separat EmberAddon so we can use them on multiple projects.

If I'm understanding the docs and issues correctly it is not possible to install our component-addon once (ex. in the root-app) and use the components inside the engines without installing the component-addon in every engine-package.json?

And if I'm installing it in every engine, it would build the component-addon in every engine-vendor.js?
So it's not possible to load the component once and use them everywhere in the app?

Related Issues: #236, #502, #58

**Comment by mydea** [comment]
As long as all the engines depend on the same version as your host app, it will only be included in your host apps vendor.js and not in the engines. ember-engines takes care of that for you :) You still need to add the addon to all engines `dependencies`, though.

IMHO the best approach for this is to use something like a yarn workspace.
We have a workspace that contains our host app, our engines and our shared addons. This way, they are always in sync, and you can easily make commits with changes across all engines/addons.

**Comment by knownasilya** [comment]
It's possible if you take an approach like this https://burstcreations.com/sharing-components-with-engines/

**Comment by Haidy777** [comment]
Thanks for your answers! The solution suggested by @mydea works perfectly. Thanks.
Maybe that should be stated somewhere in the readme or the guides :)

**Comment by villander** [comment]
@mydea @Haidy77 this solution using yarn workspaces is legal as it mitigates the problem, but should exist within ember engines. Imagine the css or components that are only used by `engine-a`, `engine-b` and `engine-c`, but are not used by the host app. You would have to load this into the host app by increasing the bundle size of it besides hurting the principle of isolation and liability. For me this issue should not be closed.

**Comment by villander** [comment]
@knownasilya you blog post about share components, is not available. Can you publish it again? can be a markdown on gist.

thank you

**Comment by swarnavallis** [comment]
> #595

 Imagine the css or components that are only used by engine-a, engine-b and engine-c, but are not used by the host app. You would have to load this into the host app by increasing the bundle size of it besides hurting the principle of isolation and liability.
 is this solved now?
