### ISSUE TITLE
Dependency error on engine after deployed

### ISSUE THREAD

**Issue by paperlambda** [ember-engines/ember-engines#608]
I am currently splitting up my app to several engines. There's an error that only displays as infinite render on parent application, then i tried to `npm link` to my local engine and i trace it to a dependency missing from the engine. i did `npm install` and things are fine, problem solved. But when deploy it, the error still occur. I am using BitBucket private repo for mounting engines.

**Comment by paperlambda** [comment]
thanks @villander, yeah i took the wrong host address for the access rights, my bad

**Comment by villander** [comment]
you're welcome @paperlambda
