### ISSUE TITLE
[RFC (Sorta)] Camelizing Engine Config is Annoying, Let's Not

### ISSUE THREAD

**Issue by jherdman** [ember-engines/ember-engines#625]
In parent application's we're asked to build out engine configurations using camelized package names. This is both surprising, and awkward — especially for scoped packages. Surprising because our packages already have names used by NPM/Yarn, e.g. "my-blog", or "my-super-awesome-engine". Awkward for scoped packages, e.g. given "@precision-nutrition/my-engine" becomes "@precisionNutrition/myEngine". Both require me to internalize camelization rules.

I hereby propose that we deprecate camelized engine names in the parent configs in favour of their natural package names.

Before
------

```javascript
const engineConfig = {
  '@precisionNutrition/myEngine': {
    // snip snip snip
  },
};
```

After
-----

```javascript
const engineConfig = {
  '@precision-nutrition/my-engine': {
    // snip snip snip
  },
};
```

Alternatives
=========

Beef up the documentation so that scoped package users aren't spelunking the code to figure out why things aren't working.

**Comment by villander** [comment]
@jherdman I thinks that it already works right now after this https://github.com/ember-engines/ember-asset-loader/pull/63

**Comment by bertdeblock** [comment]
👋! I just ran into an "issue" as well because of this. I couldn't get a dependency injection to work as `ember-engines` [camelizes the engine's name](https://github.com/ember-engines/ember-engines/blob/master/packages/ember-engines/addon/-private/engine-instance-ext.js#L61) (my engine's name contains a scope as well). I'm also in favour of dropping this and have users define the correct name themselves.

Can I help with this?

**Comment by buschtoens** [comment]
@bertdeblock personally I totally agree, that this is annoying. A PR changing this would surely be appreciated. I will also bring this up in the next ember-engines dev meeting on Friday next week. You'd also be welcome to join yourself!

As for the PR, I think we need to still support the old way, but issue a deprecation warning, when we detect its usage.

**Comment by bertdeblock** [comment]
@buschtoens I'd be happy to help with this. I already had something working locally to support both options actually, but I didn't create a PR yet because I wasn't sure if a change like this requires an RFC of some sort.

**Comment by buschtoens** [comment]
I think it does not require a fully-fledged RFC, as it doesn't really change anything in the framework core, I believe. And it's not a breaking change yet, but just a deprecation, it's also fine. But @rwjblue and @dgeb be the judges on this.

If you can hold out until next week Friday, I'd love for you to join our meeting and we can also discuss it more "officially".

**Comment by dgeb** [comment]
> As for the PR, I think we need to still support the old way, but issue a deprecation warning, when we detect its usage.

I fully support this approach. We should deprecate camelized names in favor of using exact package names.

> I think it does not require a fully-fledged RFC, as it doesn't really change anything in the framework core, I believe. And it's not a breaking change yet, but just a deprecation, it's also fine. 

I agree here as well.

**Comment by villander** [comment]
> I think it does not require a fully-fledged RFC, as it doesn't really change anything in the framework core, I believe. And it's not a breaking change yet, but just a deprecation, it's also fine. 

I fully agree! 

Feel free to create a PR @bertdeblock I'd love to review that

**Comment by bertdeblock** [comment]
Happy to create one when I find some time in the coming days 👍
