### ISSUE TITLE
Addon deduplication skips nested dependencies

### ISSUE THREAD

**Issue by mydea** [ember-engines/ember-engines#628]
It took me some time to figure out what's going on, but it seems that nested addons are not properly deduplicated in lazy engines.

I made a repo to reproduce the issue: https://github.com/mydea/test-ember-engines-addons

Basically, we have the following scenario (as an example, it behaves the same with other nested addons):

* host-app
  * ember-power-select
  * my-engine-a
     * ember-power-select-with-create
       * ember-power-select

Now I'd expect that `ember-power-select` is only included in the host-app's vendor bundle. But right now, it is additionally included in the engine's vendor bundle.

This is the final build output: 
![image](https://user-images.githubusercontent.com/2411343/54938112-0d2e4b00-4f26-11e9-85a4-ce3f74f13e34.png)

I tried to so dome debugging, and it seems that on this line: https://github.com/ember-engines/ember-engines/blob/master/lib/engine-addon.js#L60 the tree for the `ember-power-select-with-create` addon also includes all it's dependency files, for the engine.

**Comment by mydea** [comment]
After playing around with this, I guess it will be pretty hard to automatically fix this.
So what about adding a manual way to do this? We could add an option to the engine's index.js, like this:

```js
const EngineAddon = require('ember-engines/lib/engine-addon');

module.exports = EngineAddon.extend({
  name: 'my-engine-a',

  excludeFromVendorJs: ['ember-power-select/**'],

  lazyLoading: {
    enabled: true,
    includeRoutesInApplication: true
  }
});
```

And then remove these files from the engine-vendor.js bundle, like this:

```js
const buildVendorTree = memoize(function buildVendorTree() {
  // Manually invoke the child addons addon trees.
  let childAddonsAddonTrees = this.nonDuplicatedAddonInvoke('treeFor', [
    'addon',
    'buildVendorTree'
  ]);

  let childAddonsAddonTreesMerged = mergeTrees(childAddonsAddonTrees, {
    overwrite: true
  });

  if (this.options.excludeFromVendorJs) {
    childAddonsAddonTreesMerged = new Funnel(childAddonsAddonTreesMerged, {
      exclude: this.options.excludeFromVendorJs
    });
  }

  return childAddonsAddonTreesMerged;
});
```

That seemed to work fine in my example.
I could write up a PR if you agree this would make sense?

**Comment by stefanpenner** [comment]
We are currently evaluating https://github.com/ember-engines/ember-engines/pull/595

Would that address your problem? Could you also review and kick the tires on it? If so that’s would help us!

**Comment by mydea** [comment]
Ah, I did not see that PR 🤦‍♂️ sorry - I have actually seen it (and commented) some time ago, but forgot about it. That branch also fixes my example repo nicely 👍

**Comment by villander** [comment]
@mydea can you close this, please?
