### ISSUE TITLE
Need CLI command for in-repo-engine app

### ISSUE THREAD

**Issue by mesadhan** [ember-engines/ember-engines#634]
Ember Engines offers only CLI command to create Ember Engine App. There is no cli command for in-repo-engine command

```
lib
--blog
    --addon
        --routes
        --components
        --helpers
        --services
        --templates
```

Always need to create routes,components,helpers,services,templates manully.

**Comment by villander** [comment]
@mesadhan you don't can create using ember g on in-repo-engines, just on normal app or normal addon
on in-repo-engine is always manually ; )

can you close this, please?
