### ISSUE TITLE
Access an engine controller from a global function

### ISSUE THREAD

**Issue by chendraayan** [ember-engines/ember-engines#636]
If my router.js looks like this
```
//router.js
this.route('parent', function() {
  this.route('child');
});
```
And if I want to access the controller of the route 'child' inside a global function. I would use this.
`App.__container__.lookup("controller:parent/child")`

If I want to achieve the same for the controller in an engine, how would I use it, if my routes.js of my engine looks like this?
```
//routes.js
this.route('parent', function() {
  this.route('child');
});
```
I tried `App.__container__.lookup("engine:myengine").container.lookup("controller:parent/child")`

I cannot access the controller with the above line of code. Also I get a warning saying

>  DEPRECATION: Using the injected `container` is deprecated. Please use the `getOwner` helper instead to access the owner of this object.

**Comment by villander** [comment]
1) It's not a bug

2) It's not related with ember-engines, but Ember API

**Comment by bertdeblock** [comment]
Due to no response I think we can close this one?
