### ISSUE TITLE
in-repo-engine in ember addon fails to build

### ISSUE THREAD

**Issue by ghost** [ember-engines/ember-engines#649]
I'm trying to create a in-repo-engine within a ember addon and I'm not able to start nor build the addon (dummy-app). I'm getting this error:

```
Cannot read property 'enabled' of undefined


Stack Trace and Error Report: /tmp/error.dump.e5d99cfb29ccbd62b159c3945d6708f4.log
An error occurred in the constructor for test-engine at {{LOCAL_PATH_TO_ADDON}}/test/test-addon/lib/test-engine

An error occurred in the constructor for test-addon at {{LOCAL_PATH_TO_ADDON}}/test/test-addon
```

(`{{LOCAL_PATH_TO_ADDON}}` is just a placeholder I added to the original error-message, where of course locally would be the real path)

Those errors are coming from [HERE](https://github.com/ember-engines/ember-engines/blob/v0.7.1/lib/utils/find-host.js#L13) or/and [HERE](https://github.com/ember-engines/ember-engines/blob/v0.7.1/lib/utils/find-hosts-host.js#L14).

I got it working by adding a `current.lazyLoading && current.lazyLoading.enabled....` which I could find in other parts of the code like [HERE](https://github.com/ember-engines/ember-engines/blob/v0.7.1/lib/utils/deeply-non-duplicated-addon.js#L19). But not sure if this would end up as the desired behavior.

I'm not pretty sure whats wrong here or I misconfigured/missed something but I could reproduce it with the following steps:

1. `ember addon test-addon`
2. enter folder
3. `ember install ember-engines`
4. `ember g in-repo-engine test-engine`
5. `ember build --production` or `ember s`
6. error..

I tried the same for a normal app (by using the same steps but first replaced with `ember new test-app`) and it worked normally.

I add the `current.lazyLoading && current.lazyLoading.enabled` to my local `node_modules` and made some routes and tested the in-repo-engine in the addons-dummy app and seemed to work normally.

So, am I missing something? Or is this even possible a in-repo-engine within a addon?

**Comment by bertdeblock** [comment]
Tested this issue with the steps provided and if there was an error, it seems to be resolved now. I can start the server without any issues and also mount the engine inside the dummy app. Creating a production build also works fine.
