### ISSUE TITLE
Adapter not getting updates from service

### ISSUE THREAD

**Issue by arellanoelden** [ember-engines/ember-engines#655]
I have a service that my adapters read from. Whenever they read the service they only get the initial value. So if I have property `X` in my service that is `1` initially and in my controller I set it to `2`. I can see it updated in the controller but in the adapter I still only see 1

**Comment by bertdeblock** [comment]
@arellanoelden It's hard to tell if this is an actual issue with `ember-engines` based on the info provided. It doesn't sound like it is, but I could be wrong of course. Have you tried creating a reproduction? Maybe also in a regular Ember app to rule out if it's an ember-engines issue or not. If this is not an issue anymore you can close this I think.

**Comment by rwjblue** [comment]
Going to close for now, happy to reopen with a demo repo reproduction.
