### ISSUE TITLE
Engine re-exports merge into host app

### ISSUE THREAD

**Issue by ASH-Maan** [ember-engines/ember-engines#671]
Similar to this issue [Unable to override addon re-exports in the consumer application](https://github.com/ember-cli/ember-cli/issues/5336), when ember engines are being installed into the host application, the host app is merging the files exported from `engine/app/*.js` file into the `tests/dummy/app` directory and it causes an issue where unique engine files would be available to the dummy app to use.
For example, if the **last-installed engine** has `engine-name/adapters/application.js` and the host app didn't have `adapters/application.js`, then the engine's adapter file will act as the main application adapter.
A temporary fix I am using right now is to delete the `app` folder from the engine.

I am using `ember-engines@0.8.2` in the engine as well as the host app.

**Comment by bertdeblock** [comment]
Tested this and could not reproduce at the moment so I'm guessing this is resolved?

My test looks like this:
- Created a new engine using the engines blueprint
- Installed ember-data as a dependency
- Generated an application adapter
- Did a lookup of the application adapter both in the engine as well as in the host app
- Lookup in the engine returns the adapter, lookup in the host app returns undefined (expected)

The result is the same with or without the exports still being present in the app folder.

**Comment by rwjblue** [comment]
Going to close for now, happy to reopen with a demo repo reproduction.
