### ISSUE TITLE
Could not find module `<engine-name>/components/-dynamic-element` imported from `(require)`

### ISSUE THREAD

**Issue by dguettler** [ember-engines/ember-engines#676]
Not sure where this issue should be raised so I'm cross-posting it here https://github.com/tildeio/ember-element-helper/issues/7

Here is a minimal repository to trigger the issue https://github.com/dguettler/ember-dynamic-element/tree/ember-element-helper-only

Basically, if `ember-element-helper` is used within an engine's template an error is throws because in can not lookup the `-dynamic-element` module.

```
Ember      : 3.11.1
Ember Data : 3.12.0
Ember Engines : 0.8.2
```

**Comment by bertdeblock** [comment]
The linked PR mentions in its description that it should fix this issue, if so I think we can close this one?
