### ISSUE TITLE
Duplicate plugin/preset detected

### ISSUE THREAD

**Issue by amk221** [ember-engines/ember-engines#681]
```
ember new example
ember install ember-engines
ember g in-repo-engine foo
ember g in-repo-engine bar
ember s
```

Results in : 

```
Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

plugins: [
  ['some-plugin', {}],
  ['some-plugin', {}, 'some unique name'],
]
```

With

`"ember-cli": "~3.13.0"`
`"ember-engines": "^0.8.2"`

**Comment by amk221** [comment]
Any idea about this one?

Setting `lazyLoading` to false fixes the issue. But I don't want a lazy loaded engine.

**Comment by rwjblue** [comment]
@amk221 what ember-cli-htmlbars version are you using? I'm currently trying to debug a similarly reported issue related specifically to ember-cli-htmlbars >= 4.0.0 + ember-engines (over in https://github.com/ember-cli/ember-cli-htmlbars/issues/297).

**Comment by amk221** [comment]
Demo repo https://github.com/amk221/-ember-engines-duplicate-plugin-error

**Comment by rwjblue** [comment]
Thanks for that!

**Comment by amk221** [comment]
I think its `4.0.4`

**Comment by rwjblue** [comment]
@amk221 - That repo didn't error for me, I ran:

```
git clone git@github.com:amk221/-ember-engines-duplicate-plugin-error.git
cd -ember-engines-duplicate-plugin-error
npm ci
ember build
```

**Comment by amk221** [comment]
Doh, I forgot to push. (pushed)

**Comment by rwjblue** [comment]
Sent https://github.com/amk221/-ember-engines-duplicate-plugin-error/pull/1, but confirmed locally that ember-cli-htmlbars@4.0.5 fixes the issue.

**Comment by amk221** [comment]
Great, thank you!
