### ISSUE TITLE
Master fails locally

### ISSUE THREAD

**Issue by stefanpenner** [ember-engines/ember-engines#689]
After some investigation, it appears the issue related to: https://github.com/ember-cli/ember-cli/pull/8959.

TL;DR the issue appears to be `ember-cli-babel` is not being found for the in-repo engines residing at `tests/dummy/lib`. This causes the ES6 ember imports to not be rewritten by the appropriate babel plugin.

**Comment by rwjblue** [comment]
Thanks for poking at this! I am still not sure why it fails locally but not on CI 🤔

**Comment by bertdeblock** [comment]
👋 Checking if this is still an issue or if we can close this?

**Comment by rwjblue** [comment]
Ya I think we've changed things around quite a bit and CI is now properly passing.
