### ISSUE TITLE
the bump to ember-source should be a 1.0.0 release

### ISSUE THREAD

**Issue by gabrielcsapo** [ember-engines/ember-engines#700]
we should major bump the ember-source upgrade.

**Comment by villander** [comment]
I think we can close this issue @gabrielcsapo. The release 1.0 is for the Roadmap - https://discuss.emberjs.com/t/engines-1-0-roadmap/14914

**Comment by gabrielcsapo** [comment]
Might be good to open an issue that talks about 1.0.0 release here so we can track anything that needs to land before releasing
