### ISSUE TITLE
Issue with monkey patched Route API and TypeScript

### ISSUE THREAD

**Issue by LucasHill** [ember-engines/ember-engines#702]
I'm using ember-cli-typescript and ember-engines. Ember engines patches the route class to include the method 'transitionToExternal'. This does not exist on the type definitions for Ember's route. I don't believe there is a way to extend the type definition of a class in typescript without overwriting it. Could this be fixed in ember or are there any creative solutions? I do find the patching itself a little weird as it makes unpredictable issues like this appear. Thanks!

**Comment by rwjblue** [comment]
Neither ember-engines or ember-source provide the typings here. Ultimately, I think this is an issue for definitely typed not us here.
