### ISSUE TITLE
Params are always empty in transition object in beforeModel in page load

### ISSUE THREAD

**Issue by umliuxin** [ember-engines/ember-engines#703]
Hi there, 
identify an issue when trying to access query params in transition object in route beforeModel

#### some-route.js
```javascript
beforeModel(transition) {
    //transition.to.params is always empty in page load
    const myParam = transition?.to?.params?.myparam
   // do something with myParam, like redirecting
}
```
#### engine/eng/routes.js
```javascript
BuildRoute(function buildThisRoute() {
    this.route('some-route', {path: '/:myparam'})
});
```
#### app/routes.js
```javascript
BuildRoute(function buildThisRoute() {
    this.mount('eng')
});
```
I only see this issue within mounted engine, but not direct route in application.

Currently, the workaround is to use `this.paramsFor` to get the url param.
Wondering if this is a bug? or it is on purpose

**Comment by bertdeblock** [comment]
@umliuxin If this is still an issue, could you provide a reproduction? I tried this out locally and it works for me, but maybe it's a timing issue? I don't know exactly when `transition.to.params` is supposed to be populated.

**Comment by rwjblue** [comment]
Going to close for now, happy to reopen with a demo repo reproduction.
