### ISSUE TITLE
Recommendations about an architecture

### ISSUE THREAD

**Issue by peyloride** [ember-engines/ember-engines#712]
Hello all, I was trying to figure out how to nicely compose two apps from engines. Let me explain with an example;

APP A is a big app and now we want to make an another app, called B, which is a subset of APP A. Main logic is %90 percent same, but design differs almost entirely.

For example, app A has these features;
- Feature X
- Feature Y
- Feature Z

We want to build an another app (App B) with these features, but we don't want to duplicate our code, share common logic and move on;
- Feature X
- Feature Z

1) We'll split our big app into engines (probably there will be 4 engines)
2) Inside the engine split it into two in-repo engines based on some kind of environment variable. There will be two in-repo engines in each engine. Parent engine routes will be seperated into in-repo engines with an environment variable.
3) AFAIK we can not pass components from parent app into engines, we'll make an in-repo addon in every engine which contains shared/common logic. Then use this addon to use shared common logic + customized logic on in-repo engine.

On CSS side, we'll fork ember-component-css library with some customized logic (instead of selecting style.scss in every pod folder, only look app_name.scss file) I think we can completely seperate css related work. Maybe we can use some kind of base.scss + app_name.scss logic to share common.

Here is a diagram of my thinkings. I'm not really experienced in ember, so I may be totally wrong; please share your thoughts.

[architecture.pdf](https://github.com/ember-engines/ember-engines/files/4718823/artitechture.1.pdf)

Thanks

**Comment by bertdeblock** [comment]
@peyloride Since this doesn't really seem to be an actual issue with `ember-engines`, it might be better to ask this on the Ember Discord (if still relevant of course) and close this issue? I think you're better off asking for guidance on Discord than here since most people come here to look for / solve / report issues.

**Comment by peyloride** [comment]
Yeah you are right. I'm closing the issue now.
