### ISSUE TITLE
Is there a way to export in-repo engine component to the host app?

### ISSUE THREAD

**Issue by taltcher** [ember-engines/ember-engines#717]
I'm looking for a way to export components defined in my `in-repo engine` to be used in the host app - I haven't found what should I defined in both `package.json` files in order to make it work properly

**Comment by bertdeblock** [comment]
The best way to share components between an engine and its host app is to put those components into a separate addon and define said addon as a dependency for both the engine and the host app.

[More info here.](https://ember-engines.com/docs/sharing-code)

**Comment by rwjblue** [comment]
Thanks @bertdeblock! Going to close this now...
