### ISSUE TITLE
@ember/render-modifiers not working inside engines

### ISSUE THREAD

**Issue by vishwasraj** [ember-engines/ember-engines#720]
Ember version: 3.16.0

Engine `package.json` file
```
{
  "name": "blog",
  "keywords": [
    "ember-addon",
    "ember-engine"
  ],
  "dependencies": {
    "@ember/render-modifiers": "*",
    "ember-cli-htmlbars": "*",
    "ember-cli-babel": "*",
    "ember-cli-sass": "*",
    "sass": "*"
  }
}
```

Parent Application `package.json` file

using `"@ember/render-modifiers": "^1.0.2",` in Parent application

Most of the addons added work, except for `@ember/render-modifiers`

**Comment by rwjblue** [comment]
Define "not working", what happens? Is there an error? Can you provide a small reproduction app?

IMHO, this _should_ work (and is known to work in applications that I have worked in).

**Comment by bertdeblock** [comment]
@vishwasraj Any updates on this? I can confirm what @rwjblue says. Render modifiers work fine for us as well inside engines.
