### ISSUE TITLE
Support change for Ember 3.24 LinkTo refactor

### ISSUE THREAD

**Issue by chriskrycho** [ember-engines/ember-engines#740]
emberjs/ember.js#19223 made a breaking change to the private implementation of `<LinkTo>` which Engines relies on. This breaks any existing user of Engines which upgrade to Ember 3.24. We need to add a conditional handling for `gte("3.24.0")` to *not* apply the monkey-patch.

**Comment by chriskrycho** [comment]
cc. @rwjblue @villander

**Comment by chriskrycho** [comment]
With Ember 3.24 out, this is now blocking any app from upgrading which depends on Engines!

**Comment by fkm-adfinis** [comment]
It also breaks the pipelines before upgrading because of `ember:try`.

**Comment by rwjblue** [comment]
Fixed in ember-engines@0.8.9.

**Comment by chriskrycho** [comment]
Thanks so much, @rwjblue!
