### ISSUE TITLE
`@embroider/macros` macro conditions can sometimes be evaluated incorrectly

### ISSUE THREAD

**Issue by brendenpalmer** [ember-engines/ember-engines#784]
I'm filing a duplicate ticket here (I've already filed a [ticket](https://github.com/embroider-build/embroider/issues/906) for this within the `embroider` repo itself) just in-case this issue is specific to `ember-engines`. `ember-engines` uses `@embroider/macros` to have differing logic depending on `ember-source` version. It's possible for (seemingly) a previously cached macro condition to be used for an incompatible `ember-source` version.

For more info on this issue specifically, see: https://github.com/embroider-build/embroider/issues/906

**Comment by rwjblue** [comment]
Fix is released in https://github.com/ember-engines/ember-engines/releases/tag/v0.8.19
