### ISSUE TITLE
getOwner doesn't return the context for the route

### ISSUE THREAD

**Issue by h4rkl** [ember-engines/ember-engines#791]
.

**Comment by bertdeblock** [comment]
So you are trying to access an engine route from within the `<AppHeader />` component which is located outside of the engine (in the host app)? Is this correct? If so, this kind of goes against the concept of engines, they are supposed to be isolated. The main supported way for host <-> engine communication is via shared services.

**Comment by h4rkl** [comment]
.

**Comment by h4rkl** [comment]
.
