### ISSUE TITLE
cannot find module "@ember/routing/link-component" in ember ~4.1

### ISSUE THREAD

**Issue by ianknauer** [ember-engines/ember-engines#795]
I'm getting the following error when trying to use ember-engines in a brand new 4.1 app.

`Uncaught Error: Could not find module `@ember/routing/link-component` imported from `ember-engines/components/link-to-external``

As of 4.0 the link-component no longer shows up in [the docs](https://api.emberjs.com/ember/4.0/modules/@ember%2Frouting), but may be replaced by the [link-to component](https://github.com/emberjs/ember.js/blob/v4.1.0/packages/%40ember/-internals/glimmer/lib/components/link-to.ts#L40)

Example Repo is here: https://github.com/ianknauer/engines-4.0-issue

**Comment by SergeAstapov** [comment]
First attempted to be fixed in #792. There is more than that to happen.

**Comment by void-mAlex** [comment]
fixed as of 0.11.0 
fixed by #855
