### ISSUE TITLE
Ensure reopen mutations happen before instantiation.

### ISSUE THREAD

**Issue by rwjblue** [ember-engines/ember-engines#8]
- [ ] `import 'ember-engines/route-ext';`
- [ ] `import 'ember-engines/router-ext';`
- [ ] `import 'ember-engines/engine-ext';`
- [ ] `import 'ember-engines/engine-instance-ext';`
- [ ] `import 'ember-engines/keywords/mount';`

Currently, these are done in an initializer ([here](https://github.com/dgeb/ember-engines/blob/master/addon/initializers/engines.js)), but that initializer is only ran after an application is created. At some point we plan to disable reopen after any instantiation has occurred so we should try to ensure these happen before any instances have been created.

**Comment by villander** [comment]
@dgeb this can be closed as well, `import` are working for `-private`  private modules
