### ISSUE TITLE
Class extends value [object Object] is not a constructor or null

### ISSUE THREAD

**Issue by roncodes** [ember-engines/ember-engines#813]
Just had issues adding `ember-engines@0.8.23` to a new ember app (4.6.0), on start throws this error `Uncaught TypeError: Class extends value [object Object] is not a constructor or null`

This was being thrown from the `LinkToExternal` component.

I realized that `LinkComponent` was removed from `@ember/routing` package starting at ember v4, and that the package `@ember/legacy-built-in-components` is required for ember-engines to work.

After adding `@ember/legacy-built-in-components` my new ember app loaded.

This isn't stated anywhere in the ember-engine docs, shouldn't this be noted in the installation section or somewhere in the docs?

_Note: I installed ember-engines using yarn `yarn add ember-engines` and not `ember install ember-engines` ~ unsure if this matters?_

**Comment by SergeAstapov** [comment]
@roncodes thanks for logging the issue! This is indeed the miss in the documentation.

@roncodes btw, were you using https://ember-engines.com/docs/installation during your endeavor? I think that's the page where such info should be provided.

**Comment by roncodes** [comment]
@SergeAstapov Yes I was using the docs installation page. I can create if a PR if it's needed or should indeed be included in the installation instruction for v4+ users.

**Comment by Yelinz** [comment]
Same issue as https://github.com/ember-engines/ember-engines/issues/795

**Comment by void-mAlex** [comment]
fixed as of 0.11.0 
fixed by #855
