### ISSUE TITLE
TypeScript compiling not working without ember-cli-typescript in Ember 5

### ISSUE THREAD

**Issue by LucasHillDex** [ember-engines/ember-engines#857]
Now that Ember 5 supports TypeScript without ember-cli-typescript, we've converted all of our apps to use the ember-cli-babel config:
`ember-cli-babel': { enableTypeScriptTransform: true }` 
To transpile our TS files. This works in all of our apps and addons except the ember-engine addon. Is this a known issue?

**Comment by aklkv** [comment]
@LucasHillDex could you please add a bit more details, on what exactly doesn't work?

**Comment by LucasHillDex** [comment]
> @LucasHillDex could you please add a bit more details, on what exactly doesn't work?

@aklkv Yes, we have followed the migration guide for getting Typescript compiling in ember without ember-cli-typescript. https://guides.emberjs.com/release/typescript/application-development/converting-an-app/#toc_manually-enable-typescript-transpilation

This involves passing the above mentioned option to ember-cli-babel in the apps/addons build config. This migration has worked in all of our apps and addons except for the one using ember-engines. In that addon none of the typescript files can be found by the module loader at run time.

**Comment by LucasHillDex** [comment]
@aklkv I have come up with a minimal project demo to outline what I'm talking about if you would not mind checking it out.

The repo: https://github.com/LucasHillDex/engine-typescript

It has two branches. 

In the 'main' branch: A simple ember addon, version 5.4. There is a single Typescript component called Header, which is used in the dummy [application.hbs](https://github.com/LucasHillDex/engine-typescript/blob/main/tests/dummy/app/templates/application.hbs)
The TypeScript is being compiled without ember-cli-typescript via the [guide](https://guides.emberjs.com/release/typescript/application-development/converting-an-app/#toc_manually-enable-typescript-transpilation) which is most importantly configured in the [index.js](https://github.com/LucasHillDex/engine-typescript/blob/main/index.js) of the addon. In this branch all is happy and the component is rendering.

In the branch 'engine' I have added ember-engines and the necessary configuration. Now, the app is no longer able to lookup the 'Header' component, mostly likely due to the TypeScript compilation no longer happening. I wonder if in the [index.js 
 ](https://github.com/LucasHillDex/engine-typescript/blob/engine/index.js), the 'buildEngine' function is not passing the needed config to ember-cli-babel, but just a theory. 

I think considering this is the supported way of using TypeScript in ember going forward that this is a real issue and something worth investigating. 

Thank you!

**Comment by aklkv** [comment]
@LucasHillDex I have been able to run your repro with a small correction refer to engines section [here](https://github.com/emberjs/ember-cli-babel?tab=readme-ov-file#enabling-typescript-transpilation)
<img width="889" alt="Screenshot 2024-02-12 at 1 27 55 PM" src="https://github.com/ember-engines/ember-engines/assets/312210/d2b3368e-462a-4a32-978d-f3d683d2bc31">

**Comment by LucasHillDex** [comment]
@aklkv Thank you!! That was the issue.
