### ISSUE TITLE
Consuming app's resolver not updated by in-repo-engine

### ISSUE THREAD

**Issue by casimcdaniels** [ember-engines/ember-engines#91]
Following instructions on docs and used in-repo-engine to generate my engine. Everything is good except for one issue that popped up:

"attempted to mount engine at X, but engine named X could not be found"

Aha!

The generator does not update the Resolver within the app.js of parent application to 'ember-engines/resolver'

**Comment by rwjblue** [comment]
Sounds like a great thing to add, we would need to:

* create a blueprint named `ember-engines`
* have it parse/search for `ember-resolver` or `ember/resolver` and replace it with `ember-engines/resolver` in both `app/app.js` and `app/resolver.js`.

**Comment by marcemira** [comment]
I'm having the same issue. What changes do I have to make in order to resolve / finde my in-repo-addon engines? Thanks!

**Comment by benoror** [comment]
Having a similar issue https://github.com/ember-engines/ember-engines/issues/308

**Comment by trentmwillis** [comment]
This should no longer be an issue since ember-resolver can handle engines by default now.
